#! /usr/bin/env python

import sys
argstr = "".join(sys.argv[1:])
if argstr == "-":
    valstr = sys.stdin.read()
else:
    valstr = argstr

vals = [float(x) for x in valstr.split(",")]
avgvals = []
for i in range(len(vals)-1):
    avgvals.append((vals[i]+vals[i+1])/2.)
print ", ".join(["{:0.3f}".format(x) for x in avgvals])
