#! /usr/bin/env python

import sys
argstr = "".join(sys.argv[1:])
if argstr == "-":
    valstr = sys.stdin.read()
else:
    valstr = argstr

vals = [float(x) for x in valstr.split(",")]
tmp = []
for i in range(len(vals)//2):
    x = (vals[i] + vals[-i-1])/2.
    tmp.append(x)
if len(vals) % 2 != 0:
    tmp.append(vals[len(vals)//2])
foldedvals = reversed(tmp)
print ", ".join(["{:0.3f}".format(x) for x in foldedvals])
