Rivet: Rivet::CumulantAnalysis::ECorrelator Class Reference
Rivet::CumulantAnalysis::ECorrelator Class Reference
A helper class to calculate all event averages of correlators.
#include <Correlators.hh>
Public Member Functions
ECorrelator (vector< int > h, vector< double > binIn)
Constructor. Takes as argument the desired harmonic and number of correlated particles as a generic framework style vector, eg, {2, -2} for <<2>>_2, no binning.
ECorrelator (vector< int > h1In, vector< int > h2In, vector< double > binIn)
Constructor for gapped correlator.
void fill (const double &obs, const Correlators &c, double weight=1.0)
Fill the appropriate bin given an input (per event) observable, e.g. centrality.
void fill (const double &obs, const Correlators &c1, const Correlators &c2, double weight=1.0)
Fill the appropriate bin given an input (per event) observable, e.g. centrality, with a rapidity gap between two Correlators.
void fill (const Correlators &c, const double &weight=1.0)
Fill the bins with the appropriate correlator.
void fill (const Correlators &c1, const Correlators &c2, const double &weight=1.0)
Fill bins with the appropriate correlator, and a rapidity gap between two Correlators.
const vector< CorBin > getBins () const
Get a copy of the bin contents.
const vector< CorBinBase * > getBinPtrs ()
Return the bins as pointers to the base class.
const vector< double > getBinX () const
Get a copy of the bin x-values.
const vector< int > getH1 () const
Get a copy of the h1 harmonic vector.
const vector< int > getH2 () const
Get a copy of the h2 harmonic vector.
void setReference (CorBin refIn)
Replace reference flow bin with another, e.g. calculated in another phase space or with other pid.
const CorBin getReference () const
Extract the reference flow from a differential event averaged correlator.
void setProfs (vector< string > prIn)
Set the prIn list of profile histograms associated with the internal bins.
bool fillFromProfile (YODA::AnalysisObjectPtr yao, string name)
Fill bins with content from preloaded histograms.
Public Attributes
vector< string > profs
Detailed Description
A helper class to calculate all event averages of correlators.
Useful to construct cumulants. It can be binned in any variable.
Constructor & Destructor Documentation
ECorrelator() [1/2]
Rivet::CumulantAnalysis::ECorrelator::ECorrelator (vector< int > h, vector< double > binIn) inline
Constructor. Takes as argument the desired harmonic and number of correlated particles as a generic framework style vector, eg, {2, -2} for <<2>>_2, no binning.
Todo:
Implement functionality for this if needed.
Constructor
Takes as argument the desired harmonic and number of correlated particles as a generic framework style vector, e.g. {2, -2} for <<2>>_2 and binning.
ECorrelator() [2/2]
Rivet::CumulantAnalysis::ECorrelator::ECorrelator (vector< int > h1In, vector< int > h2In, vector< double > binIn) inline
Constructor for gapped correlator.
Takes as argument the desired harmonics for the two final states, and binning.
Member Function Documentation
fill() [1/2]
void Rivet::CumulantAnalysis::ECorrelator::fill (const Correlators & c, const double & weight = 1.0) inline
Fill the bins with the appropriate correlator.
Takes the binning directly from the Correlators object, and fills also the reference flow.
References Rivet::Correlators::intCorrelator(), and Rivet::Correlators::pTBinnedCorrelators().
fill() [2/2]
void Rivet::CumulantAnalysis::ECorrelator::fill (const Correlators & c1, const Correlators & c2, const double & weight = 1.0) inline
Fill bins with the appropriate correlator, and a rapidity gap between two Correlators.
Takes the binning directly from the Correlators object, and also the reference flow.
References Rivet::Correlators::intCorrelatorGap(), and Rivet::Correlators::pTBinnedCorrelatorsGap().
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/Tools/Correlators.hh