Rivet: Rivet::JetShape Class Reference
Rivet::JetShape Class Reference abstract
Calculate transverse jet profiles.
#include <JetShape.hh>
Public Member Functions
void clear ()
Reset projection between events.
void calc (const Jets &jets)
Do the calculation directly on a supplied collection of Jet objects.
size_t numBins () const
Number of equidistant radius bins.
size_t numJets () const
Number of jets which passed cuts.
double rMin () const
\(r_\text{min} \) value.
double rMax () const
\(r_\text{max} \) value.
double ptMin () const
\(p_\perp^\text{min} \) value.
double ptMax () const
\(p_\perp^\text{max} \) value.
double rBinMin (size_t rbin) const
Central \(r \) value for bin rbin.
double rBinMax (size_t rbin) const
Central \(r \) value for bin rbin.
double rBinMid (size_t rbin) const
Central \(r \) value for bin rbin.
double diffJetShape (size_t ijet, size_t rbin) const
Return value of differential jet shape profile histo bin.
double intJetShape (size_t ijet, size_t rbin) const
Return value of integrated jet shape profile histo bin.
virtual std::string name () const
Get the name of the projection.
bool valid () const
Get the state of the projetion.
bool failed () const
Get the state of the projetion.
void markAsOwned () const
Mark this object as owned by a proj-handler.
Constructors etc.
JetShape (const JetAlg &jetalg, double rmin, double rmax, size_t nbins, double ptmin=0, double ptmax=DBL_MAX, double absrapmin=-DBL_MAX, double absrapmax=-DBL_MAX, RapScheme rapscheme=RAPIDITY)
Constructor from histo range and number of bins.
JetShape (const JetAlg &jetalg, vector< double > binedges, double ptmin=0, double ptmax=DBL_MAX, double absrapmin=-DBL_MAX, double absrapmax=-DBL_MAX, RapScheme rapscheme=RAPIDITY)
Constructor from vector of bin edges.
DEFAULT_RIVET_PROJ_CLONE (JetShape)
Clone on the heap.
Standard constructors and destructors.
virtual unique_ptr< Projection > clone () const =0
Clone on the heap.
Projection operation and comparison
bool before (const Projection &p) const
Beam configuration
Todo:
Does it really make sense to restrict Projections to particular beam configs? Do we use this in practice?
virtual const std::set< PdgIdPair > beamPairs () const
Projection & addPdgIdPair (PdgId beam1, PdgId beam2)
Projection "getting" functions
std::set< ConstProjectionPtr > getProjections () const
Get the contained projections, including recursion.
bool hasProjection (const std::string &name) const
Does this applier have a projection registered under the name name?
template<typename PROJ >
const PROJ & getProjection (const std::string &name) const
const Projection & getProjection (const std::string &name) const
template<typename PROJ >
const PROJ & get (const std::string &name) const
Projection applying functions
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const Projection &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const PROJ &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const std::string &name) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const Projection &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const PROJ &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const std::string &name) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const std::string &name, const Event &evt) const
Apply the supplied projection on event evt (convenience arg-reordering alias).
Protected Member Functions
void project (const Event &e)
Apply the projection to the event.
CmpState compare (const Projection &p) const
Compare projections.
Log & getLog () const
Get a Log object based on the getName() property of the calling projection object.
void setName (const std::string &name)
Used by derived classes to set their name.
void fail ()
Set the projection in an unvalid state.
Cmp< Projection > mkNamedPCmp (const Projection &otherparent, const std::string &pname) const
Cmp< Projection > mkPCmp (const Projection &otherparent, const std::string &pname) const
ProjectionHandler & getProjHandler () const
Get a reference to the ProjectionHandler for this thread.
Projection registration functions
template<typename PROJ >
const PROJ & declareProjection (const PROJ &proj, const std::string &name)
Register a contained projection.
template<typename PROJ >
const PROJ & declare (const PROJ &proj, const std::string &name)
Register a contained projection (user-facing version)
template<typename PROJ >
const PROJ & declare (const std::string &name, const PROJ &proj)
Register a contained projection (user-facing, arg-reordered version)
Detailed Description
Calculate transverse jet profiles.
Calculate the differential and integral jet shapes in \(P_{\perp}\) for a given set of jets. This particular jet shape projection calculates jet shapes relative to jet centroids, using only the particles associated to each jet, for the hardest \(n \) jets.
The rapidity scheme (\(\eta \) or \(y \)) has to be specified when invoking the constructor.
The differential jet shape around a given jet axis at distance interval \(r \pm \delta{r}/2 \) is defined as
\[ \rho(r) = \frac{1}{\delta r} \frac{1}{N_\mathrm{jets}} \sum_\mathrm{jets} \frac{P_\perp(r - \delta r/2, r+\delta r/2)}{p_\perp(0, R)} \]
with \(0 \le r \le R \) and \(P_\perp(r_1, r_2) = \sum_{\in [r_1, r_2)} p_\perp \).
The integral jet shape around a given jet axes until distance \(r \) is defined as
\[ \Psi(r) = \frac{1}{N_\mathrm{jets}} \sum_\mathrm{jets} \frac{P_\perp(0, r)}{p_\perp(0, R)} \]
with \(0 \le r \le R \) and \(P_\perp(r_1, r_2) = \sum_{\in [r_1, r_2)} p_\perp \).
The constructor expects also the binning in radius \(r \) to be supplied.
Member Function Documentation
addPdgIdPair()
Projection& Rivet::Projection::addPdgIdPair (PdgId beam1, PdgId beam2) inline inherited
Add a colliding beam pair.
Todo:
This deserves a better name!
applyProjection() [1/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const Projection & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [2/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const PROJ & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [3/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const std::string & name) const inline inherited
Apply the named projection on event evt.
Deprecated:
Prefer the simpler apply<> form
beamPairs()
virtual const std::set<PdgIdPair> Rivet::Projection::beamPairs () const virtual inherited
Return the allowed beam pairs on which this projection can operate, not including recursion. Derived classes should ensure that all contained projections are registered in the _projections set for the beam constraint chaining to work.
Todo:
Remove the beam constraints system from projections.
Referenced by Rivet::Projection::failed().
before()
bool Rivet::Projection::before (const Projection & p) const inherited
Determine whether this object should be ordered before the object p given as argument. If p is of a different class than this, the before() function of the corresponding type_info objects is used. Otherwise, if the objects are of the same class, the virtual compare(const Projection &) will be returned.
Referenced by Rivet::Projection::fail(), and Rivet::Projection::failed().
declare() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection (user-facing version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection().
Referenced by Rivet::CentralityProjection::add(), Rivet::VetoedFinalState::addVetoOnThisFinalState(), Rivet::BeamThrust::BeamThrust(), Rivet::CentralEtHCM::CentralEtHCM(), Rivet::CentralityEstimator::CentralityEstimator(), Rivet::ChargedLeptons::ChargedLeptons(), Rivet::ALICE::CLMultiplicity< INNER >::CLMultiplicity(), Rivet::DISDiffHadron::DISDiffHadron(), Rivet::DISFinalState::DISFinalState(), Rivet::DISKinematics::DISKinematics(), Rivet::DISLepton::DISLepton(), Rivet::GammaGammaKinematics::GammaGammaKinematics(), Rivet::GammaGammaLeptons::GammaGammaLeptons(), Rivet::GeneratedCentrality::GeneratedCentrality(), Rivet::HadronicFinalState::HadronicFinalState(), Rivet::HeavyHadrons::HeavyHadrons(), Rivet::Hemispheres::Hemispheres(), Rivet::LeadingParticlesFinalState::LeadingParticlesFinalState(), Rivet::LossyFinalState< ConstRandomFilter >::LossyFinalState(), Rivet::MC_pPbMinBiasTrigger::MC_pPbMinBiasTrigger(), Rivet::MC_SumETFwdPbCentrality::MC_SumETFwdPbCentrality(), Rivet::ATLAS::MinBiasTrigger::MinBiasTrigger(), Rivet::MissingMomentum::MissingMomentum(), Rivet::NeutralFinalState::NeutralFinalState(), Rivet::NonHadronicFinalState::NonHadronicFinalState(), Rivet::ParisiTensor::ParisiTensor(), Rivet::PercentileProjection::PercentileProjection(), Rivet::PrimaryHadrons::PrimaryHadrons(), Rivet::CentralityBinner< T, MDist >::setProjection(), Rivet::SmearedJets::SmearedJets(), Rivet::SmearedMET::SmearedMET(), Rivet::SmearedParticles::SmearedParticles(), Rivet::Spherocity::Spherocity(), Rivet::ATLAS::SumET_PB_Centrality::SumET_PB_Centrality(), Rivet::ATLAS::SumET_PBPB_Centrality::SumET_PBPB_Centrality(), Rivet::TauFinder::TauFinder(), Rivet::Thrust::Thrust(), Rivet::TriggerCDFRun0Run1::TriggerCDFRun0Run1(), Rivet::TriggerCDFRun2::TriggerCDFRun2(), Rivet::UndressBeamLeptons::UndressBeamLeptons(), Rivet::ALICE::V0AndTrigger::V0AndTrigger(), Rivet::ALICE::V0Trigger< MODE >::V0Trigger(), Rivet::VetoedFinalState::VetoedFinalState(), and Rivet::VisibleFinalState::VisibleFinalState().
declare() [2/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const std::string & name, const PROJ & proj) inline protected inherited
Register a contained projection (user-facing, arg-reordered version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection(), and Rivet::ProjectionApplier::name().
declareProjection()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declareProjection (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection.
The type of the argument is used to instantiate a new projection internally: this new object is applied to events rather than the argument object. Hence you are advised to only use locally-scoped Projection objects in your Projection and Analysis constructors, and to avoid polymorphism (e.g. handling ConcreteProjection via a pointer or reference to type Projection) since this will screw up the internal type management.
Todo:
Add SFINAE to require that PROJ inherit from Projection
Referenced by Rivet::ProjectionApplier::declare().
get()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::get (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument (user-facing alias).
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::name().
getProjection() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument.
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
Referenced by Rivet::pcmp().
getProjection() [2/2]
const Projection& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection (non-templated, so returns as a reference to a Projection base class).
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
mkNamedPCmp()
Cmp<Projection> Rivet::Projection::mkNamedPCmp (const Projection & otherparent, const std::string & pname) const protected inherited
Shortcut to make a named Cmp<Projection> comparison with the *this object automatically passed as one of the parent projections.
Referenced by Rivet::FParameter::compare(), Rivet::STAR_BES_Centrality::compare(), Rivet::CentralEtHCM::compare(), Rivet::BeamThrust::compare(), Rivet::MC_SumETFwdPbCentrality::compare(), Rivet::ATLAS::SumET_PB_Centrality::compare(), Rivet::CentralityEstimator::compare(), Rivet::Spherocity::compare(), Rivet::GammaGammaFinalState::compare(), Rivet::LossyFinalState< ConstRandomFilter >::compare(), Rivet::BRAHMSCentrality::compare(), Rivet::Thrust::compare(), Rivet::DISFinalState::compare(), Rivet::MC_pPbMinBiasTrigger::compare(), Rivet::ATLAS::SumET_PBPB_Centrality::compare(), Rivet::Hemispheres::compare(), Rivet::HeavyHadrons::compare(), Rivet::PercentileProjection::compare(), Rivet::ATLAS::MinBiasTrigger::compare(), Rivet::EventMixingBase::compare(), Rivet::GeneratedCentrality::compare(), and Rivet::Projection::fail().
mkPCmp()
Cmp<Projection> Rivet::Projection::mkPCmp (const Projection & otherparent, const std::string & pname) const protected inherited
Shortcut to make a named Cmp<Projection> comparison with the *this object automatically passed as one of the parent projections.
Note
Alias for mkNamedPCmp
Referenced by Rivet::SmearedMET::compare(), Rivet::SmearedParticles::compare(), Rivet::SmearedJets::compare(), Rivet::Correlators::compare(), Rivet::ALICE::PrimaryParticles::compare(), and Rivet::Projection::fail().
project()
void Rivet::JetShape::project (const Event & e) protected virtual
Apply the projection to the event.
Todo:
Provide int and diff jet shapes with some sort of area normalisation?
Implements Rivet::Projection.
Referenced by intJetShape().
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/Projections/JetShape.hh