Rivet: Rivet::AnalysisLoader Class Reference
Rivet::AnalysisLoader Class Reference
Internal class which loads and registers analyses from plugin libs.
#include <AnalysisLoader.hh>
Static Public Member Functions
static vector< string > analysisNames ()
Get the available analyses' names.
static set< string > allAnalysisNames ()
static set< string > getAllAnalysisNames ()
static vector< string > stdAnalysisNames ()
Get the standard analyses' names (from a release-specific list file)
static unique_ptr< Analysis > getAnalysis (const string &analysisname)
static vector< unique_ptr< Analysis > > getAllAnalyses ()
Get all the available analyses.
Friends
class AnalysisBuilderBase
Allow the analysis builders to call the private _registerBuilder function.
Detailed Description
Internal class which loads and registers analyses from plugin libs.
Member Function Documentation
allAnalysisNames()
static set<string> Rivet::AnalysisLoader::allAnalysisNames () static
Get all the available analyses' names (as a set)
Todo:
Why this duplicate?
Referenced by getAllAnalysisNames().
getAllAnalysisNames()
static set<string> Rivet::AnalysisLoader::getAllAnalysisNames () inline static
Deprecated:
Use allAnalysisNames()
References allAnalysisNames(), getAllAnalyses(), getAnalysis(), and stdAnalysisNames().
getAnalysis()
static unique_ptr<Analysis> Rivet::AnalysisLoader::getAnalysis (const string & analysisname) static
Get an analysis by name. Warning: a name arg which matches no known analysis will return a null pointer. Check your return values before using them!
Referenced by getAllAnalysisNames().
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/AnalysisLoader.hh