Rivet: Rivet::MC_JetSplittings Class Reference
Rivet::MC_JetSplittings Class Reference
Base class providing common functionality for MC jet validation analyses.
#include <MC_JetSplittings.hh>
Public Member Functions
MC_JetSplittings (const string &name, size_t njet, const string &jetpro_name)
Default constructor.
const AnalysisInfo & info () const
Get the actual AnalysisInfo object in which all this metadata is stored.
AnalysisInfo & info ()
virtual std::string name () const
Get the name of the analysis.
virtual std::string getRefDataName () const
Get name of reference data file, which could be different from plugin name.
virtual void setRefDataName (const std::string &ref_data="")
Set name of reference data file, which could be different from plugin name.
virtual std::string inspireId () const
Get the Inspire ID code for this analysis.
virtual std::string spiresId () const
Get the SPIRES ID code for this analysis (~deprecated).
virtual std::vector< std::string > authors () const
Names & emails of paper/analysis authors.
virtual std::string summary () const
Get a short description of the analysis.
virtual std::string description () const
Get a full description of the analysis.
virtual std::string runInfo () const
Information about the events needed as input for this analysis.
virtual std::string experiment () const
Experiment which performed and published this analysis.
virtual std::string collider () const
Collider on which the experiment ran.
virtual std::string year () const
When the original experimental analysis was published.
virtual double luminosityfb () const
The integrated luminosity in inverse femtobarn.
virtual double luminosity () const
The integrated luminosity in inverse picobarn.
virtual std::vector< std::string > references () const
Journal, and preprint references.
virtual std::string bibKey () const
BibTeX citation key for this article.
virtual std::string bibTeX () const
BibTeX citation entry for this article.
virtual std::string status () const
Whether this analysis is trusted (in any way!)
virtual std::vector< std::string > todos () const
Any work to be done on this analysis.
virtual std::vector< std::string > validation () const
make-style commands for validating this analysis.
virtual bool reentrant () const
Does this analysis have a reentrant finalize()?
virtual std::string refFile () const
Location of reference data YODA file.
virtual const std::vector< PdgIdPair > & requiredBeams () const
Return the allowed pairs of incoming beams required by this analysis.
virtual Analysis & setRequiredBeams (const std::vector< PdgIdPair > &requiredBeams)
Declare the allowed pairs of incoming beams required by this analysis.
virtual const std::vector< std::pair< double, double > > & requiredEnergies () const
Sets of valid beam energy pairs, in GeV.
virtual const std::vector< std::string > & keywords () const
Get vector of analysis keywords.
virtual Analysis & setRequiredEnergies (const std::vector< std::pair< double, double > > &requiredEnergies)
Declare the list of valid beam energy pairs, in GeV.
const ParticlePair & beams () const
Incoming beams for this run.
const PdgIdPair beamIds () const
Incoming beam IDs for this run.
double sqrtS () const
Centre of mass energy for this run.
bool merging () const
Check if we are running rivet-merge.
bool isCompatible (const ParticlePair &beams) const
Check if analysis is compatible with the provided beam particle IDs and energies.
bool isCompatible (PdgId beam1, PdgId beam2, double e1, double e2) const
Check if analysis is compatible with the provided beam particle IDs and energies.
bool isCompatible (const PdgIdPair &beams, const std::pair< double, double > &energies) const
Check if analysis is compatible with the provided beam particle IDs and energies.
AnalysisHandler & handler () const
Access the controlling AnalysisHandler object.
template<>
const char * getOption (std::string optname, const char *def)
const CentralityProjection & declareCentrality (const SingleValueProjection &proj, string calAnaName, string calHistName, const string projName, bool increasing=false)
Book a CentralityProjection.
template<class T >
Percentile< T > bookPercentile (string projName, vector< pair< float, float > > centralityBins, vector< tuple< int, int, int > > ref)
Book a Percentile wrapper around AnalysisObjects.
double dbl (double x)
double dbl (const YODA::Counter &c)
double dbl (const YODA::Scatter1D &s)
void scale (CounterPtr cnt, CounterAdapter factor)
Multiplicatively scale the given counter, cnt, by factor factor.
void scale (const std::vector< CounterPtr > &cnts, CounterAdapter factor)
template<typename T >
void scale (const std::map< T, CounterPtr > &maps, CounterAdapter factor)
Iteratively scale the counters in the map maps, by factor factor.
template<std::size_t array_size>
void scale (const CounterPtr(&cnts)[array_size], CounterAdapter factor)
void scale (Histo1DPtr histo, CounterAdapter factor)
Multiplicatively scale the given histogram, histo, by factor factor.
void scale (const std::vector< Histo1DPtr > &histos, CounterAdapter factor)
template<typename T >
void scale (const std::map< T, Histo1DPtr > &maps, CounterAdapter factor)
Iteratively scale the histograms in the map, maps, by factor factor.
template<std::size_t array_size>
void scale (const Histo1DPtr(&histos)[array_size], CounterAdapter factor)
void scale (Histo2DPtr histo, CounterAdapter factor)
Multiplicatively scale the given histogram, histo, by factor factor.
void scale (const std::vector< Histo2DPtr > &histos, CounterAdapter factor)
template<typename T >
void scale (const std::map< T, Histo2DPtr > &maps, CounterAdapter factor)
Iteratively scale the histograms in the map, maps, by factor factor.
template<std::size_t array_size>
void scale (const Histo2DPtr(&histos)[array_size], CounterAdapter factor)
void normalize (Histo1DPtr histo, CounterAdapter norm=1.0, bool includeoverflows=true)
Normalize the given histogram, histo, to area = norm.
void normalize (const std::vector< Histo1DPtr > &histos, CounterAdapter norm=1.0, bool includeoverflows=true)
template<typename T >
void normalize (const std::map< T, Histo1DPtr > &maps, CounterAdapter norm=1.0, bool includeoverflows=true)
Normalize the histograms in map, maps, to area = norm.
template<std::size_t array_size>
void normalize (const Histo1DPtr(&histos)[array_size], CounterAdapter norm=1.0, bool includeoverflows=true)
void normalize (Histo2DPtr histo, CounterAdapter norm=1.0, bool includeoverflows=true)
Normalize the given histogram, histo, to area = norm.
void normalize (const std::vector< Histo2DPtr > &histos, CounterAdapter norm=1.0, bool includeoverflows=true)
template<typename T >
void normalize (const std::map< T, Histo2DPtr > &maps, CounterAdapter norm=1.0, bool includeoverflows=true)
Normalize the histograms in map, maps, to area = norm.
template<std::size_t array_size>
void normalize (const Histo2DPtr(&histos)[array_size], CounterAdapter norm=1.0, bool includeoverflows=true)
void divide (CounterPtr c1, CounterPtr c2, Scatter1DPtr s) const
void divide (const YODA::Counter &c1, const YODA::Counter &c2, Scatter1DPtr s) const
void divide (Histo1DPtr h1, Histo1DPtr h2, Scatter2DPtr s) const
void divide (const YODA::Histo1D &h1, const YODA::Histo1D &h2, Scatter2DPtr s) const
void divide (Profile1DPtr p1, Profile1DPtr p2, Scatter2DPtr s) const
void divide (const YODA::Profile1D &p1, const YODA::Profile1D &p2, Scatter2DPtr s) const
void divide (Histo2DPtr h1, Histo2DPtr h2, Scatter3DPtr s) const
void divide (const YODA::Histo2D &h1, const YODA::Histo2D &h2, Scatter3DPtr s) const
void divide (Profile2DPtr p1, Profile2DPtr p2, Scatter3DPtr s) const
void divide (const YODA::Profile2D &p1, const YODA::Profile2D &p2, Scatter3DPtr s) const
void efficiency (Histo1DPtr h1, Histo1DPtr h2, Scatter2DPtr s) const
void efficiency (const YODA::Histo1D &h1, const YODA::Histo1D &h2, Scatter2DPtr s) const
void asymm (Histo1DPtr h1, Histo1DPtr h2, Scatter2DPtr s) const
void asymm (const YODA::Histo1D &h1, const YODA::Histo1D &h2, Scatter2DPtr s) const
void integrate (Histo1DPtr h, Scatter2DPtr s) const
void integrate (const Histo1D &h, Scatter2DPtr s) const
const vector< MultiweightAOPtr > & analysisObjects () const
List of registered analysis data objects.
void markAsOwned () const
Mark this object as owned by a proj-handler.
Analysis methods
virtual void init ()
virtual void analyze (const Event &event)
virtual void finalize ()
Allow RAW histograms to be read in to local objects.
virtual void rawHookIn (YODA::AnalysisObjectPtr yao)
Provide access to RAW histograms before writing out to file.
virtual void rawHookOut (vector< MultiweightAOPtr > raos, size_t iW)
Accessing options for this Analysis instance.
const std::map< std::string, std::string > & options ()
Return the map of all options given to this analysis.
std::string getOption (std::string optname)
Get an option for this analysis instance as a string.
template<typename T >
T getOption (std::string optname, T def)
Get an option for this analysis instance converted to a specific type.
Projection "getting" functions
std::set< ConstProjectionPtr > getProjections () const
Get the contained projections, including recursion.
bool hasProjection (const std::string &name) const
Does this applier have a projection registered under the name name?
template<typename PROJ >
const PROJ & getProjection (const std::string &name) const
const Projection & getProjection (const std::string &name) const
template<typename PROJ >
const PROJ & get (const std::string &name) const
Projection applying functions
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const Projection &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const PROJ &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const std::string &name) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const Projection &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const PROJ &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const std::string &name) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const std::string &name, const Event &evt) const
Apply the supplied projection on event evt (convenience arg-reordering alias).
Protected Member Functions
Log & getLog () const
Get a Log object based on the name() property of the calling analysis object.
double crossSection () const
Get the process cross-section in pb. Throws if this hasn't been set.
double crossSectionPerEvent () const
size_t numEvents () const
Get the number of events seen (via the analysis handler).
double sumW () const
Get the sum of event weights seen (via the analysis handler).
double sumOfWeights () const
Alias.
double sumW2 () const
Get the sum of squared event weights seen (via the analysis handler).
const std::string histoDir () const
Get the canonical histogram "directory" path for this analysis.
const std::string histoPath (const std::string &hname) const
Get the canonical histogram path for the named histogram in this analysis.
const std::string histoPath (unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId) const
Get the canonical histogram path for the numbered histogram in this analysis.
const std::string mkAxisCode (unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId) const
Get the internal histogram name for given d, x and y (cf. HepData)
const std::map< std::string, YODA::AnalysisObjectPtr > & refData () const
Get all reference data objects for this analysis.
template<typename T = YODA::Scatter2D>
const T & refData (const string &hname) const
template<typename T = YODA::Scatter2D>
const T & refData (unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId) const
CounterPtr & book (CounterPtr &, const std::string &name)
Book a counter.
CounterPtr & book (CounterPtr &, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId)
Histo1DPtr & book (Histo1DPtr &, const std::string &name, size_t nbins, double lower, double upper)
Book a 1D histogram with nbins uniformly distributed across the range lower - upper .
Histo1DPtr & book (Histo1DPtr &, const std::string &name, const std::vector< double > &binedges)
Book a 1D histogram with non-uniform bins defined by the vector of bin edges binedges .
Histo1DPtr & book (Histo1DPtr &, const std::string &name, const std::initializer_list< double > &binedges)
Book a 1D histogram with non-uniform bins defined by the vector of bin edges binedges .
Histo1DPtr & book (Histo1DPtr &, const std::string &name, const Scatter2D &refscatter)
Book a 1D histogram with binning from a reference scatter.
Histo1DPtr & book (Histo1DPtr &, const std::string &name)
Book a 1D histogram, using the binnings in the reference data histogram.
Histo1DPtr & book (Histo1DPtr &, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId)
Histo2DPtr & book (Histo2DPtr &, const std::string &name, size_t nxbins, double xlower, double xupper, size_t nybins, double ylower, double yupper)
Histo2DPtr & book (Histo2DPtr &, const std::string &name, const std::vector< double > &xbinedges, const std::vector< double > &ybinedges)
Histo2DPtr & book (Histo2DPtr &, const std::string &name, const std::initializer_list< double > &xbinedges, const std::initializer_list< double > &ybinedges)
Histo2DPtr & book (Histo2DPtr &, const std::string &name, const Scatter3D &refscatter)
Book a 2D histogram with binning from a reference scatter.
Histo2DPtr & book (Histo2DPtr &, const std::string &name)
Book a 2D histogram, using the binnings in the reference data histogram.
Histo2DPtr & book (Histo2DPtr &, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId)
Profile1DPtr & book (Profile1DPtr &, const std::string &name, size_t nbins, double lower, double upper)
Book a 1D profile histogram with nbins uniformly distributed across the range lower - upper .
Profile1DPtr & book (Profile1DPtr &, const std::string &name, const std::vector< double > &binedges)
Book a 1D profile histogram with non-uniform bins defined by the vector of bin edges binedges .
Profile1DPtr & book (Profile1DPtr &, const std::string &name, const std::initializer_list< double > &binedges)
Book a 1D profile histogram with non-uniform bins defined by the vector of bin edges binedges .
Profile1DPtr & book (Profile1DPtr &, const std::string &name, const Scatter2D &refscatter)
Book a 1D profile histogram with binning from a reference scatter.
Profile1DPtr & book (Profile1DPtr &, const std::string &name)
Book a 1D profile histogram, using the binnings in the reference data histogram.
Profile1DPtr & book (Profile1DPtr &, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId)
Profile2DPtr & book (Profile2DPtr &, const std::string &name, size_t nxbins, double xlower, double xupper, size_t nybins, double ylower, double yupper)
Profile2DPtr & book (Profile2DPtr &, const std::string &name, const std::vector< double > &xbinedges, const std::vector< double > &ybinedges)
Profile2DPtr & book (Profile2DPtr &, const std::string &name, const std::initializer_list< double > &xbinedges, const std::initializer_list< double > &ybinedges)
Scatter2DPtr & book (Scatter2DPtr &s2d, const string &hname, bool copy_pts=false)
Book a 2-dimensional data point set with the given name.
Scatter2DPtr & book (Scatter2DPtr &s2d, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId, bool copy_pts=false)
Book a 2-dimensional data point set, using the binnings in the reference data histogram.
Scatter2DPtr & book (Scatter2DPtr &s2d, const string &hname, size_t npts, double lower, double upper)
Book a 2-dimensional data point set with equally spaced x-points in a range.
Scatter2DPtr & book (Scatter2DPtr &s2d, const string &hname, const std::vector< double > &binedges)
Book a 2-dimensional data point set based on provided contiguous "bin edges".
Scatter2DPtr & book (Scatter2DPtr &s2d, const string &hname, const Scatter2D &refscatter)
Book a 2-dimensional data point set with x-points from an existing scatter and a new path.
Scatter3DPtr & book (Scatter3DPtr &s3d, const std::string &hname, bool copy_pts=false)
Book a 3-dimensional data point set with the given name.
Scatter3DPtr & book (Scatter3DPtr &s3d, unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId, unsigned int zAxisId, bool copy_pts=false)
Book a 3-dimensional data point set, using the binnings in the reference data histogram.
Scatter3DPtr & book (Scatter3DPtr &s3d, const std::string &hname, size_t xnpts, double xlower, double xupper, size_t ynpts, double ylower, double yupper)
Book a 3-dimensional data point set with equally spaced x-points in a range.
Scatter3DPtr & book (Scatter3DPtr &s3d, const std::string &hname, const std::vector< double > &xbinedges, const std::vector< double > &ybinedges)
Book a 3-dimensional data point set based on provided contiguous "bin edges".
Scatter3DPtr & book (Scatter3DPtr &s3d, const std::string &hname, const Scatter3D &refscatter)
Book a 3-dimensional data point set with x-points from an existing scatter and a new path.
template<typename YODAT >
shared_ptr< YODAT > getPreload (string path) const
Get a preloaded YODA object.
template<typename YODAT >
rivet_shared_ptr< Wrapper< YODAT > > registerAO (const YODAT &yao)
Register a new data object, optionally read in preloaded data.
template<typename AO = MultiweightAOPtr>
AO addAnalysisObject (const AO &aonew)
Register a data object in the histogram system.
void removeAnalysisObject (const std::string &path)
Unregister a data object from the histogram system (by name)
void removeAnalysisObject (const MultiweightAOPtr &ao)
Unregister a data object from the histogram system (by pointer)
template<typename AO = MultiweightAOPtr>
const AO getAnalysisObject (const std::string &aoname) const
Get a Rivet data object from the histogram system.
template<typename AO = MultiweightAOPtr>
AO getAnalysisObject (const std::string &ananame, const std::string &aoname)
ProjectionHandler & getProjHandler () const
Get a reference to the ProjectionHandler for this thread.
Projection registration functions
template<typename PROJ >
const PROJ & declareProjection (const PROJ &proj, const std::string &name)
Register a contained projection.
template<typename PROJ >
const PROJ & declare (const PROJ &proj, const std::string &name)
Register a contained projection (user-facing version)
template<typename PROJ >
const PROJ & declare (const std::string &name, const PROJ &proj)
Register a contained projection (user-facing, arg-reordered version)
Protected Attributes
size_t m_njet
The number of jets for which histograms are to be initialised.
const std::string m_jetpro_name
Detailed Description
Base class providing common functionality for MC jet validation analyses.
Member Function Documentation
analyze()
virtual void Rivet::MC_JetSplittings::analyze (const Event & event) virtual
Analyze one event. A concrete class should here apply the necessary projections on the event and fill the relevant histograms. An overridden function must make sure it first calls the base class function.
Implements Rivet::Analysis.
applyProjection() [1/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const Projection & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [2/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const PROJ & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [3/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const std::string & name) const inline inherited
Apply the named projection on event evt.
Deprecated:
Prefer the simpler apply<> form
crossSectionPerEvent()
double Rivet::Analysis::crossSectionPerEvent () const protected inherited
Get the process cross-section per generated event in pb. Throws if this hasn't been set.
Referenced by Rivet::Analysis::handler().
declare() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection (user-facing version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection().
Referenced by Rivet::CentralityProjection::add(), Rivet::VetoedFinalState::addVetoOnThisFinalState(), Rivet::BeamThrust::BeamThrust(), Rivet::CentralEtHCM::CentralEtHCM(), Rivet::CentralityEstimator::CentralityEstimator(), Rivet::ChargedLeptons::ChargedLeptons(), Rivet::ALICE::CLMultiplicity< INNER >::CLMultiplicity(), Rivet::DISDiffHadron::DISDiffHadron(), Rivet::DISFinalState::DISFinalState(), Rivet::DISKinematics::DISKinematics(), Rivet::DISLepton::DISLepton(), Rivet::GammaGammaKinematics::GammaGammaKinematics(), Rivet::GammaGammaLeptons::GammaGammaLeptons(), Rivet::GeneratedCentrality::GeneratedCentrality(), Rivet::HadronicFinalState::HadronicFinalState(), Rivet::HeavyHadrons::HeavyHadrons(), Rivet::Hemispheres::Hemispheres(), Rivet::LeadingParticlesFinalState::LeadingParticlesFinalState(), Rivet::LossyFinalState< ConstRandomFilter >::LossyFinalState(), Rivet::MC_pPbMinBiasTrigger::MC_pPbMinBiasTrigger(), Rivet::MC_SumETFwdPbCentrality::MC_SumETFwdPbCentrality(), Rivet::ATLAS::MinBiasTrigger::MinBiasTrigger(), Rivet::MissingMomentum::MissingMomentum(), Rivet::NeutralFinalState::NeutralFinalState(), Rivet::NonHadronicFinalState::NonHadronicFinalState(), Rivet::ParisiTensor::ParisiTensor(), Rivet::PercentileProjection::PercentileProjection(), Rivet::PrimaryHadrons::PrimaryHadrons(), Rivet::CentralityBinner< T, MDist >::setProjection(), Rivet::SmearedJets::SmearedJets(), Rivet::SmearedMET::SmearedMET(), Rivet::SmearedParticles::SmearedParticles(), Rivet::Spherocity::Spherocity(), Rivet::ATLAS::SumET_PB_Centrality::SumET_PB_Centrality(), Rivet::ATLAS::SumET_PBPB_Centrality::SumET_PBPB_Centrality(), Rivet::TauFinder::TauFinder(), Rivet::Thrust::Thrust(), Rivet::TriggerCDFRun0Run1::TriggerCDFRun0Run1(), Rivet::TriggerCDFRun2::TriggerCDFRun2(), Rivet::UndressBeamLeptons::UndressBeamLeptons(), Rivet::ALICE::V0AndTrigger::V0AndTrigger(), Rivet::ALICE::V0Trigger< MODE >::V0Trigger(), Rivet::VetoedFinalState::VetoedFinalState(), and Rivet::VisibleFinalState::VisibleFinalState().
declare() [2/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const std::string & name, const PROJ & proj) inline protected inherited
Register a contained projection (user-facing, arg-reordered version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection(), and Rivet::ProjectionApplier::name().
declareProjection()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declareProjection (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection.
The type of the argument is used to instantiate a new projection internally: this new object is applied to events rather than the argument object. Hence you are advised to only use locally-scoped Projection objects in your Projection and Analysis constructors, and to avoid polymorphism (e.g. handling ConcreteProjection via a pointer or reference to type Projection) since this will screw up the internal type management.
Todo:
Add SFINAE to require that PROJ inherit from Projection
Referenced by Rivet::ProjectionApplier::declare().
divide() [1/4]
void Rivet::Analysis::divide (Histo1DPtr h1, Histo1DPtr h2, Scatter2DPtr s) const inherited
Helper for histogram division.
Note
Assigns to the (already registered) output scatter, s. Preserves the path information of the target.
divide() [2/4]
void Rivet::Analysis::divide (Profile1DPtr p1, Profile1DPtr p2, Scatter2DPtr s) const inherited
Helper for profile histogram division.
Note
Assigns to the (already registered) output scatter, s. Preserves the path information of the target.
divide() [3/4]
void Rivet::Analysis::divide (Histo2DPtr h1, Histo2DPtr h2, Scatter3DPtr s) const inherited
Helper for 2D histogram division.
Note
Assigns to the (already registered) output scatter, s. Preserves the path information of the target.
divide() [4/4]
void Rivet::Analysis::divide (Profile2DPtr p1, Profile2DPtr p2, Scatter3DPtr s) const inherited
Helper for 2D profile histogram division.
Note
Assigns to the (already registered) output scatter, s. Preserves the path information of the target.
finalize()
virtual void Rivet::MC_JetSplittings::finalize () virtual
Finalize this analysis object. A concrete class should here make all necessary operations on the histograms. Writing the histograms to a file is, however, done by the Rivet class. An overridden function must make sure it first calls the base class function.
Reimplemented from Rivet::Analysis.
get()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::get (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument (user-facing alias).
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::name().
getOption()
template<typename T > T Rivet::Analysis::getOption (std::string optname, T def) inline inherited
Get an option for this analysis instance converted to a specific type.
The return type is given by the specified def value, or by an explicit template type-argument, e.g. getOption<double>("FOO", 3).
References Rivet::Analysis::declareCentrality().
getProjection() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument.
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
Referenced by Rivet::pcmp().
getProjection() [2/2]
const Projection& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection (non-templated, so returns as a reference to a Projection base class).
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
init()
virtual void Rivet::MC_JetSplittings::init () virtual
Initialize this analysis object. A concrete class should here book all necessary histograms. An overridden function must make sure it first calls the base class function.
Reimplemented from Rivet::Analysis.
normalize() [1/2]
void Rivet::Analysis::normalize (const std::vector< Histo2DPtr > & histos, CounterAdapter norm = 1.0, bool includeoverflows = true) inline inherited
Normalize the given histograms, histos, to area = norm.
Note
Constness intentional, if weird, to allow passing rvalue refs of smart ptrs (argh)
Todo:
Use SFINAE for a generic iterable of Histo2DPtrs
References Rivet::Analysis::normalize().
normalize() [2/2]
template<std::size_t array_size> void Rivet::Analysis::normalize (const Histo2DPtr(&) histos[array_size], CounterAdapter norm = 1.0, bool includeoverflows = true) inline inherited
Todo:
YUCK!
References Rivet::Analysis::normalize(), and Rivet::Analysis::scale().
numEvents()
size_t Rivet::Analysis::numEvents () const protected inherited
Get the number of events seen (via the analysis handler).
Note
Use in the finalize phase only.
Referenced by Rivet::Analysis::handler().
scale() [1/4]
void Rivet::Analysis::scale (const std::vector< Histo1DPtr > & histos, CounterAdapter factor) inline inherited
Multiplicatively scale the given histograms, histos, by factor factor.
Note
Constness intentional, if weird, to allow passing rvalue refs of smart ptrs (argh)
Todo:
Use SFINAE for a generic iterable of Histo1DPtrs
References Rivet::Analysis::scale().
scale() [2/4]
template<std::size_t array_size> void Rivet::Analysis::scale (const Histo1DPtr(&) histos[array_size], CounterAdapter factor) inline inherited
Todo:
YUCK!
References Rivet::Analysis::normalize(), and Rivet::Analysis::scale().
scale() [3/4]
void Rivet::Analysis::scale (const std::vector< Histo2DPtr > & histos, CounterAdapter factor) inline inherited
Multiplicatively scale the given histograms, histos, by factor factor.
Note
Constness intentional, if weird, to allow passing rvalue refs of smart ptrs (argh)
Todo:
Use SFINAE for a generic iterable of Histo2DPtrs
References Rivet::Analysis::scale().
scale() [4/4]
template<std::size_t array_size> void Rivet::Analysis::scale (const Histo2DPtr(&) histos[array_size], CounterAdapter factor) inline inherited
Todo:
YUCK!
References Rivet::Analysis::asymm(), Rivet::Analysis::divide(), Rivet::Analysis::efficiency(), Rivet::Analysis::integrate(), and Rivet::Analysis::scale().
sumW()
double Rivet::Analysis::sumW () const protected inherited
Get the sum of event weights seen (via the analysis handler).
Note
Use in the finalize phase only.
Referenced by Rivet::Analysis::handler(), and Rivet::Analysis::sumOfWeights().
sumW2()
double Rivet::Analysis::sumW2 () const protected inherited
Get the sum of squared event weights seen (via the analysis handler).
Note
Use in the finalize phase only.
Referenced by Rivet::Analysis::sumOfWeights().
Member Data Documentation
m_jetpro_name
const std::string Rivet::MC_JetSplittings::m_jetpro_name protected
The name of the jet projection to be used for this analysis (this projection has to be registered by the derived analysis!)
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/Analyses/MC_JetSplittings.hh