Rivet: Rivet::HeavyHadrons Class Reference
Rivet::HeavyHadrons Class Reference abstract
Project out the last pre-decay b and c hadrons.
#include <HeavyHadrons.hh>
Public Member Functions
virtual bool accept (const Particle &p) const
virtual std::string name () const
Get the name of the projection.
bool valid () const
Get the state of the projetion.
bool failed () const
Get the state of the projetion.
void markAsOwned () const
Mark this object as owned by a proj-handler.
Constructors and destructors.
HeavyHadrons (const Cut &c=Cuts::open())
DEFAULT_RIVET_PROJ_CLONE (HeavyHadrons)
Clone on the heap.
b hadron accessors
const Particles & bHadrons () const
Get all weakly decaying b hadrons (return by reference)
Particles bHadrons (const Cut &c) const
Get weakly decaying b hadrons with a Cut applied (return by value)
Particles bHadrons (double ptmin) const
Particles bHadrons (const ParticleSelector &s) const
Get weakly decaying b hadrons with a general filter function applied (return by value)
const Particles & cHadrons () const
Get all weakly decaying c hadrons (return by reference)
Particles cHadrons (const Cut &c) const
Get weakly decaying c hadrons with a Cut applied (return by value)
Particles cHadrons (double ptmin) const
Particles cHadrons (const ParticleSelector &s) const
Get weakly decaying c hadrons with a general filter function applied (return by value)
Standard constructors etc.
DEFAULT_RIVET_PROJ_CLONE (FinalState)
Clone on the heap.
Object lifetime management
virtual unique_ptr< Projection > clone () const =0
Clone on the heap.
Particle accessors
size_t size () const
Count the final-state particles.
size_t size (const Cut &c) const
Count the final-state particles after a Cut is applied.
size_t size (const ParticleSelector &s) const
Count the final-state particles after a selection functor is applied.
bool empty () const
Is this final state empty?
bool empty (const Cut &c) const
Is this final state empty after a Cut is applied?
bool empty (const ParticleSelector &s) const
Is this final state empty after a selection functor is applied?
virtual const Particles & particles () const
Get the particles in no particular order, with no cuts.
Particles particles (const Cut &c) const
Get the particles with selection cuts.
Particles particles (const ParticleSelector &selector) const
Get the particles with selection cuts via a functor.
Particles particles (const ParticleSorter &sorter, const Cut &c=Cuts::open()) const
Particles particles (const Cut &c, const ParticleSorter &sorter) const
Particles particles (const ParticleSelector &selector, const ParticleSorter &sorter) const
Particles particles (const ParticleSorter &sorter, const ParticleSelector &selector) const
Particles rawParticles () const
Particles particlesByPt (const Cut &c=Cuts::open()) const
Particles particlesByPt (const ParticleSelector &selector) const
Particles particlesByPt (double ptmin) const
Projection operation and comparison
bool before (const Projection &p) const
Beam configuration
Todo:
Does it really make sense to restrict Projections to particular beam configs? Do we use this in practice?
virtual const std::set< PdgIdPair > beamPairs () const
Projection & addPdgIdPair (PdgId beam1, PdgId beam2)
Projection "getting" functions
std::set< ConstProjectionPtr > getProjections () const
Get the contained projections, including recursion.
bool hasProjection (const std::string &name) const
Does this applier have a projection registered under the name name?
template<typename PROJ >
const PROJ & getProjection (const std::string &name) const
const Projection & getProjection (const std::string &name) const
template<typename PROJ >
const PROJ & get (const std::string &name) const
Projection applying functions
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const Projection &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const PROJ &proj) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > applyProjection (const Event &evt, const std::string &name) const
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const Projection &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const PROJ &proj) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const Event &evt, const std::string &name) const
Apply the supplied projection on event evt (user-facing alias).
template<typename PROJ = Projection>
std::enable_if_t< std::is_base_of< Projection, PROJ >::value, const PROJ & > apply (const std::string &name, const Event &evt) const
Apply the supplied projection on event evt (convenience arg-reordering alias).
Protected Member Functions
virtual void project (const Event &e)
Apply the projection to the event.
virtual CmpState compare (const Projection &p) const
Compare projections (only difference is in UFS definition)
Log & getLog () const
Get a Log object based on the getName() property of the calling projection object.
void setName (const std::string &name)
Used by derived classes to set their name.
void fail ()
Set the projection in an unvalid state.
Cmp< Projection > mkNamedPCmp (const Projection &otherparent, const std::string &pname) const
Cmp< Projection > mkPCmp (const Projection &otherparent, const std::string &pname) const
ProjectionHandler & getProjHandler () const
Get a reference to the ProjectionHandler for this thread.
Projection registration functions
template<typename PROJ >
const PROJ & declareProjection (const PROJ &proj, const std::string &name)
Register a contained projection.
template<typename PROJ >
const PROJ & declare (const PROJ &proj, const std::string &name)
Register a contained projection (user-facing version)
template<typename PROJ >
const PROJ & declare (const std::string &name, const PROJ &proj)
Register a contained projection (user-facing, arg-reordered version)
For JetAlg compatibility
Todo:
Replace with cuts() accessor virtual Cut cuts() const { return _cuts; }
const collection_type & entities () const
Template-usable interface common to JetAlg.
typedef Particle entity_type
typedef Particles collection_type
Detailed Description
Project out the last pre-decay b and c hadrons.
This currently defines a c-hadron as one which contains a c quark and not a b quark.
Todo:
This assumes that the heavy hadrons are unstable... should we also look for stable ones in case the decays are disabled?
Constructor & Destructor Documentation
HeavyHadrons()
Rivet::HeavyHadrons::HeavyHadrons (const Cut & c = Cuts::open()) inline
Constructor with specification of the minimum and maximum pseudorapidity \(\eta \) and the min \(p_T \) (in GeV).
References Rivet::ProjectionApplier::declare(), DEFAULT_RIVET_PROJ_CLONE(), and Rivet::Projection::setName().
Member Function Documentation
accept()
virtual bool Rivet::FinalState::accept (const Particle & p) const virtual inherited
Decide if a particle is to be accepted or not.
Todo:
Rename to _accept or acceptFinal?
Reimplemented in Rivet::FinalPartons.
addPdgIdPair()
Projection& Rivet::Projection::addPdgIdPair (PdgId beam1, PdgId beam2) inline inherited
Add a colliding beam pair.
Todo:
This deserves a better name!
applyProjection() [1/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const Projection & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [2/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const PROJ & proj) const inline inherited
Apply the supplied projection on event evt.
Deprecated:
Prefer the simpler apply<> form
applyProjection() [3/3]
template<typename PROJ = Projection> std::enable_if_t<std::is_base_of<Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::applyProjection (const Event & evt, const std::string & name) const inline inherited
Apply the named projection on event evt.
Deprecated:
Prefer the simpler apply<> form
beamPairs()
virtual const std::set<PdgIdPair> Rivet::Projection::beamPairs () const virtual inherited
Return the allowed beam pairs on which this projection can operate, not including recursion. Derived classes should ensure that all contained projections are registered in the _projections set for the beam constraint chaining to work.
Todo:
Remove the beam constraints system from projections.
Referenced by Rivet::Projection::failed().
before()
bool Rivet::Projection::before (const Projection & p) const inherited
Determine whether this object should be ordered before the object p given as argument. If p is of a different class than this, the before() function of the corresponding type_info objects is used. Otherwise, if the objects are of the same class, the virtual compare(const Projection &) will be returned.
Referenced by Rivet::Projection::fail(), and Rivet::Projection::failed().
bHadrons()
Particles Rivet::HeavyHadrons::bHadrons (double ptmin) const inline
Get weakly decaying b hadrons with a pTmin cut (return by value)
Deprecated:
Prefer bHadrons(Cuts::pT > x)
References bHadrons().
cHadrons()
Particles Rivet::HeavyHadrons::cHadrons (double ptmin) const inline
Get weakly decaying c hadrons with a pTmin cut (return by value)
Deprecated:
Prefer cHadrons(Cuts::pT > x)
References cHadrons().
declare() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection (user-facing version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection().
Referenced by Rivet::CentralityProjection::add(), Rivet::VetoedFinalState::addVetoOnThisFinalState(), Rivet::BeamThrust::BeamThrust(), Rivet::CentralEtHCM::CentralEtHCM(), Rivet::CentralityEstimator::CentralityEstimator(), Rivet::ChargedLeptons::ChargedLeptons(), Rivet::ALICE::CLMultiplicity< INNER >::CLMultiplicity(), Rivet::DISDiffHadron::DISDiffHadron(), Rivet::DISFinalState::DISFinalState(), Rivet::DISKinematics::DISKinematics(), Rivet::DISLepton::DISLepton(), Rivet::GammaGammaKinematics::GammaGammaKinematics(), Rivet::GammaGammaLeptons::GammaGammaLeptons(), Rivet::GeneratedCentrality::GeneratedCentrality(), Rivet::HadronicFinalState::HadronicFinalState(), HeavyHadrons(), Rivet::Hemispheres::Hemispheres(), Rivet::LeadingParticlesFinalState::LeadingParticlesFinalState(), Rivet::LossyFinalState< ConstRandomFilter >::LossyFinalState(), Rivet::MC_pPbMinBiasTrigger::MC_pPbMinBiasTrigger(), Rivet::MC_SumETFwdPbCentrality::MC_SumETFwdPbCentrality(), Rivet::ATLAS::MinBiasTrigger::MinBiasTrigger(), Rivet::MissingMomentum::MissingMomentum(), Rivet::NeutralFinalState::NeutralFinalState(), Rivet::NonHadronicFinalState::NonHadronicFinalState(), Rivet::ParisiTensor::ParisiTensor(), Rivet::PercentileProjection::PercentileProjection(), Rivet::PrimaryHadrons::PrimaryHadrons(), Rivet::CentralityBinner< T, MDist >::setProjection(), Rivet::SmearedJets::SmearedJets(), Rivet::SmearedMET::SmearedMET(), Rivet::SmearedParticles::SmearedParticles(), Rivet::Spherocity::Spherocity(), Rivet::ATLAS::SumET_PB_Centrality::SumET_PB_Centrality(), Rivet::ATLAS::SumET_PBPB_Centrality::SumET_PBPB_Centrality(), Rivet::TauFinder::TauFinder(), Rivet::Thrust::Thrust(), Rivet::TriggerCDFRun0Run1::TriggerCDFRun0Run1(), Rivet::TriggerCDFRun2::TriggerCDFRun2(), Rivet::UndressBeamLeptons::UndressBeamLeptons(), Rivet::ALICE::V0AndTrigger::V0AndTrigger(), Rivet::ALICE::V0Trigger< MODE >::V0Trigger(), Rivet::VetoedFinalState::VetoedFinalState(), and Rivet::VisibleFinalState::VisibleFinalState().
declare() [2/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declare (const std::string & name, const PROJ & proj) inline protected inherited
Register a contained projection (user-facing, arg-reordered version)
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::declareProjection(), and Rivet::ProjectionApplier::name().
declareProjection()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::declareProjection (const PROJ & proj, const std::string & name) inline protected inherited
Register a contained projection.
The type of the argument is used to instantiate a new projection internally: this new object is applied to events rather than the argument object. Hence you are advised to only use locally-scoped Projection objects in your Projection and Analysis constructors, and to avoid polymorphism (e.g. handling ConcreteProjection via a pointer or reference to type Projection) since this will screw up the internal type management.
Todo:
Add SFINAE to require that PROJ inherit from Projection
Referenced by Rivet::ProjectionApplier::declare().
get()
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::get (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument (user-facing alias).
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionApplier::name().
getProjection() [1/2]
template<typename PROJ > const PROJ& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection, specifying return type via a template argument.
Todo:
Add SFINAE to require that PROJ inherit from Projection
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
Referenced by Rivet::pcmp().
getProjection() [2/2]
const Projection& Rivet::ProjectionApplier::getProjection (const std::string & name) const inline inherited
Get the named projection (non-templated, so returns as a reference to a Projection base class).
References Rivet::ProjectionHandler::getProjection(), and Rivet::ProjectionApplier::getProjHandler().
mkNamedPCmp()
Cmp<Projection> Rivet::Projection::mkNamedPCmp (const Projection & otherparent, const std::string & pname) const protected inherited
Shortcut to make a named Cmp<Projection> comparison with the *this object automatically passed as one of the parent projections.
Referenced by Rivet::FParameter::compare(), Rivet::STAR_BES_Centrality::compare(), Rivet::CentralEtHCM::compare(), Rivet::BeamThrust::compare(), Rivet::MC_SumETFwdPbCentrality::compare(), Rivet::ATLAS::SumET_PB_Centrality::compare(), Rivet::CentralityEstimator::compare(), Rivet::Spherocity::compare(), Rivet::GammaGammaFinalState::compare(), Rivet::LossyFinalState< ConstRandomFilter >::compare(), Rivet::BRAHMSCentrality::compare(), Rivet::Thrust::compare(), Rivet::DISFinalState::compare(), Rivet::MC_pPbMinBiasTrigger::compare(), Rivet::ATLAS::SumET_PBPB_Centrality::compare(), Rivet::Hemispheres::compare(), compare(), Rivet::PercentileProjection::compare(), Rivet::ATLAS::MinBiasTrigger::compare(), Rivet::EventMixingBase::compare(), Rivet::GeneratedCentrality::compare(), and Rivet::Projection::fail().
mkPCmp()
Cmp<Projection> Rivet::Projection::mkPCmp (const Projection & otherparent, const std::string & pname) const protected inherited
Shortcut to make a named Cmp<Projection> comparison with the *this object automatically passed as one of the parent projections.
Note
Alias for mkNamedPCmp
Referenced by Rivet::SmearedMET::compare(), Rivet::SmearedParticles::compare(), Rivet::SmearedJets::compare(), Rivet::Correlators::compare(), Rivet::ALICE::PrimaryParticles::compare(), and Rivet::Projection::fail().
particles() [1/6]
Particles Rivet::ParticleFinder::particles (const Cut & c) const inline inherited
Get the particles with selection cuts.
Note
Returns a copy rather than a reference, due to the cuts.
References Rivet::filter_select(), and Rivet::ParticleFinder::particles().
particles() [2/6]
Particles Rivet::ParticleFinder::particles (const ParticleSelector & selector) const inline inherited
Get the particles with selection cuts via a functor.
Note
Returns a copy rather than a reference, due to the cuts.
References Rivet::filter_select(), and Rivet::ParticleFinder::particles().
particles() [3/6]
Particles Rivet::ParticleFinder::particles (const ParticleSorter & sorter, const Cut & c = Cuts::open()) const inline inherited
Get the particles, ordered by supplied sorting function object
Note
Returns a copy rather than a reference, due to cuts and sorting.
References Rivet::ParticleFinder::particles(), and Rivet::sortBy().
particles() [4/6]
Particles Rivet::ParticleFinder::particles (const Cut & c, const ParticleSorter & sorter) const inline inherited
Get the particles, ordered by supplied sorting function object
Note
Returns a copy rather than a reference, due to cuts and sorting.
References Rivet::ParticleFinder::particles(), and Rivet::sortBy().
particles() [5/6]
Particles Rivet::ParticleFinder::particles (const ParticleSelector & selector, const ParticleSorter & sorter) const inline inherited
Get the particles, ordered by a sorting functor and filtered by a selection functor
Note
Returns a copy rather than a reference, due to cuts and sorting.
References Rivet::ParticleFinder::particles(), and Rivet::sortBy().
particles() [6/6]
Particles Rivet::ParticleFinder::particles (const ParticleSorter & sorter, const ParticleSelector & selector) const inline inherited
Get the particles, ordered by a sorting functor and filtered by a selection functor
Note
Returns a copy rather than a reference, due to cuts and sorting.
References Rivet::ParticleFinder::particles(), and Rivet::sortBy().
particlesByPt() [1/3]
Particles Rivet::ParticleFinder::particlesByPt (const Cut & c = Cuts::open()) const inline inherited
Get the particles, ordered by decreasing \(p_T \) and with optional cuts
This is a very common use-case, so is available as syntatic sugar for particles(c, cmpMomByPt).
References Rivet::cmpMomByPt(), and Rivet::ParticleFinder::particles().
Referenced by Rivet::SmearedParticles::project(), and Rivet::SmearedParticles::truthParticles().
particlesByPt() [2/3]
Particles Rivet::ParticleFinder::particlesByPt (const ParticleSelector & selector) const inline inherited
Get the particles, ordered by decreasing \(p_T \) and with optional cuts
This is a very common use-case, so is available as syntatic sugar for particles(f, cmpMomByPt).
References Rivet::cmpMomByPt(), and Rivet::ParticleFinder::particles().
particlesByPt() [3/3]
Particles Rivet::ParticleFinder::particlesByPt (double ptmin) const inline inherited
Get the particles, ordered by decreasing \(p_T \) and with a cut on minimum \(p_T \)
This is a very common use-case, so is available as syntatic sugar for particles(Cuts::pT >= ptmin, cmpMomByPt).
References Rivet::cmpMomByPt(), and Rivet::ParticleFinder::particles().
rawParticles()
Particles Rivet::ParticleFinder::rawParticles () const inline inherited
Get the raw particles in no particular order, with no cuts
Note
Raw particles are the final-state constituents, as opposed to potentially composite particles returned as the finder's particles()
References Rivet::ParticleFinder::particles().
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/Projections/HeavyHadrons.hh