Rivet: Rivet::DressedLepton Class Reference
Rivet::DressedLepton Class Reference
A charged lepton meta-particle created by clustering photons close to the bare lepton.
#include <DressedLeptons.hh>
Public Member Functions
DressedLepton (const Particle &dlepton)
Copy constructor (from Particle)
DressedLepton (const Particle &lepton, const Particles &photons, bool momsum=true)
void addPhoton (const Particle &p, bool momsum=true)
const Particle & bareLepton () const
Retrieve the bare lepton.
const Particle & constituentLepton () const
const Particles photons () const
Retrieve the clustered photons.
const Particles constituentPhotons () const
Kinematic properties
const FourMomentum & momentum () const
The momentum.
Particle & setMomentum (const FourMomentum &momentum)
Set the momentum.
Particle & setMomentum (double E, double px, double py, double pz)
Set the momentum via components.
Particle & transformBy (const LorentzTransform &lt)
Apply an active Lorentz transform to this particle.
Positional properties
const FourVector & origin () const
The origin position (and time).
Particle & setOrigin (const FourVector &position)
Set the origin position.
Particle & setOrigin (double t, double x, double y, double z)
Set the origin position via components.
Displacement-projection properties
Vector3 closestApproach () const
Find the point of closest approach to the primary vertex.
Other representations and implicit casts to momentum-like objects
virtual fastjet::PseudoJet pseudojet () const
Converter to FastJet3 PseudoJet.
operator PseudoJet () const
Cast operator to FastJet3 PseudoJet.
Particle & setGenParticle (ConstGenParticlePtr gp)
Set a const pointer to the original GenParticle.
ConstGenParticlePtr genParticle () const
Get a const pointer to the original GenParticle.
operator ConstGenParticlePtr () const
Particle ID code accessors
PdgId pid () const
This Particle's PDG ID code.
PdgId abspid () const
Absolute value of the PDG ID code.
Charge
double charge () const
The charge of this Particle.
double abscharge () const
The absolute charge of this Particle.
int charge3 () const
Three times the charge of this Particle (i.e. integer multiple of smallest quark charge).
int abscharge3 () const
Three times the absolute charge of this Particle (i.e. integer multiple of smallest quark charge).
bool isCharged () const
Is this Particle charged?
Particle species
bool isHadron () const
Is this a hadron?
bool isMeson () const
Is this a meson?
bool isBaryon () const
Is this a baryon?
bool isLepton () const
Is this a lepton?
bool isChargedLepton () const
Is this a charged lepton?
bool isNeutrino () const
Is this a neutrino?
bool hasBottom () const
Does this (hadron) contain a b quark?
bool hasCharm () const
Does this (hadron) contain a c quark?
bool isVisible () const
Is this particle potentially visible in a detector?
bool isParton () const
Is this a parton? (Hopefully not very often... fiducial FTW)
Constituents (for composite particles)
virtual void setConstituents (const Particles &cs, bool setmom=false)
Set direct constituents of this particle.
virtual void addConstituent (const Particle &c, bool addmom=false)
Add a single direct constituent to this particle.
virtual void addConstituents (const Particles &cs, bool addmom=false)
Add direct constituents to this particle.
bool isComposite () const
Determine if this Particle is a composite of other Rivet Particles.
const Particles & constituents () const
Direct constituents of this particle, returned by reference.
const Particles constituents (const ParticleSorter &sorter) const
Direct constituents of this particle, sorted by a functor.
const Particles constituents (const Cut &c) const
Direct constituents of this particle, filtered by a Cut.
const Particles constituents (const Cut &c, const ParticleSorter &sorter) const
Direct constituents of this particle, sorted by a functor.
const Particles constituents (const ParticleSelector &selector) const
Direct constituents of this particle, filtered by a selection functor.
const Particles constituents (const ParticleSelector &selector, const ParticleSorter &sorter) const
Direct constituents of this particle, filtered and sorted by functors.
Particles rawConstituents () const
Fundamental constituents of this particle.
const Particles rawConstituents (const ParticleSorter &sorter) const
Fundamental constituents of this particle, sorted by a functor.
const Particles rawConstituents (const Cut &c) const
Fundamental constituents of this particle, filtered by a Cut.
const Particles rawConstituents (const Cut &c, const ParticleSorter &sorter) const
Fundamental constituents of this particle, sorted by a functor.
const Particles rawConstituents (const ParticleSelector &selector) const
Fundamental constituents of this particle, filtered by a selection functor.
const Particles rawConstituents (const ParticleSelector &selector, const ParticleSorter &sorter) const
Fundamental constituents of this particle, filtered and sorted by functors.
Ancestry (for fundamental particles with a HepMC link)
Particles parents (const Cut &c=Cuts::OPEN) const
Particles parents (const ParticleSelector &f) const
bool hasParentWith (const ParticleSelector &f) const
bool hasParentWith (const Cut &c) const
bool hasParentWithout (const ParticleSelector &f) const
bool hasParentWithout (const Cut &c) const
bool hasParent (PdgId pid) const
Particles ancestors (const Cut &c=Cuts::OPEN, bool only_physical=true) const
Particles ancestors (const ParticleSelector &f, bool only_physical=true) const
bool hasAncestorWith (const ParticleSelector &f, bool only_physical=true) const
bool hasAncestorWith (const Cut &c, bool only_physical=true) const
bool hasAncestorWithout (const ParticleSelector &f, bool only_physical=true) const
bool hasAncestorWithout (const Cut &c, bool only_physical=true) const
bool hasAncestor (PdgId pid, bool only_physical=true) const
bool fromBottom () const
Determine whether the particle is from a b-hadron decay.
bool fromCharm () const
Determine whether the particle is from a c-hadron decay.
bool fromHadron () const
Determine whether the particle is from a hadron decay.
bool fromTau (bool prompt_taus_only=false) const
Determine whether the particle is from a tau decay.
bool fromPromptTau () const
Determine whether the particle is from a prompt tau decay.
bool fromHadronicTau (bool prompt_taus_only=false) const
Determine whether the particle is from a tau which decayed hadronically.
DEPRECATED ("Too vague: use fromHadron() || fromPromptTau(), or isDirect()") bool fromDecay() const
Determine whether the particle is from a hadron or tau decay.
bool isDirect (bool allow_from_direct_tau=false, bool allow_from_direct_mu=false) const
Shorthand definition of 'promptness' based on set definition flags.
bool isPrompt (bool allow_from_prompt_tau=false, bool allow_from_prompt_mu=false) const
Alias for isDirect.
Decay info
bool isStable () const
Whether this particle is stable according to the generator.
Particles children (const Cut &c=Cuts::OPEN) const
Get a list of the direct descendants from the current particle (with optional selection Cut)
Particles children (const ParticleSelector &f) const
Get a list of the direct descendants from the current particle (with selector function)
bool hasChildWith (const ParticleSelector &f) const
bool hasChildWith (const Cut &c) const
bool hasChildWithout (const ParticleSelector &f) const
bool hasChildWithout (const Cut &c) const
Particles allDescendants (const Cut &c=Cuts::OPEN, bool remove_duplicates=true) const
Get a list of all the descendants from the current particle (with optional selection Cut)
Particles allDescendants (const ParticleSelector &f, bool remove_duplicates=true) const
Get a list of all the descendants from the current particle (with selector function)
bool hasDescendantWith (const ParticleSelector &f, bool remove_duplicates=true) const
bool hasDescendantWith (const Cut &c, bool remove_duplicates=true) const
bool hasDescendantWithout (const ParticleSelector &f, bool remove_duplicates=true) const
bool hasDescendantWithout (const Cut &c, bool remove_duplicates=true) const
Particles stableDescendants (const Cut &c=Cuts::OPEN) const
Particles stableDescendants (const ParticleSelector &f) const
Get a list of all the stable descendants from the current particle (with selector function)
bool hasStableDescendantWith (const ParticleSelector &f) const
bool hasStableDescendantWith (const Cut &c) const
bool hasStableDescendantWithout (const ParticleSelector &f) const
bool hasStableDescendantWithout (const Cut &c) const
double flightLength () const
Flight length (divide by mm or cm to get the appropriate units)
Duplicate testing
bool isFirstWith (const ParticleSelector &f) const
Determine whether a particle is the first in a decay chain to meet the function requirement.
bool isFirstWithout (const ParticleSelector &f) const
Determine whether a particle is the first in a decay chain not to meet the function requirement.
bool isLastWith (const ParticleSelector &f) const
Determine whether a particle is the last in a decay chain to meet the function requirement.
bool isLastWithout (const ParticleSelector &f) const
Determine whether a particle is the last in a decay chain not to meet the function requirement.
Comparison
bool isSame (const Particle &other) const
Effective momentum accessors
const FourMomentum & mom () const
Get equivalent single momentum four-vector (const) (alias).
operator const FourMomentum & () const
Cast operator for conversion to FourMomentum.
Convenience access to the effective 4-vector properties
double E () const
Get the energy directly.
double energy () const
Get the energy directly (alias).
double E2 () const
Get the energy-squared.
double energy2 () const
Get the energy-squared (alias).
double pt () const
Get the \(p_T \) directly.
double pT () const
Get the \(p_T \) directly (alias).
double perp () const
Get the \(p_T \) directly (alias).
double pt2 () const
Get the \(p_T^2 \) directly.
double pT2 () const
Get the \(p_T^2 \) directly (alias).
double perp2 () const
Get the \(p_T^2 \) directly (alias).
double Et () const
Get the \(E_T \) directly.
double Et2 () const
Get the \(E_T^2 \) directly.
double mass () const
Get the mass directly.
double mass2 () const
Get the mass**2 directly.
double pseudorapidity () const
Get the \(\eta \) directly.
double eta () const
Get the \(\eta \) directly (alias).
double abspseudorapidity () const
Get the \(|\eta| \) directly.
double abseta () const
Get the \(|\eta| \) directly (alias).
double rapidity () const
Get the \(y \) directly.
double rap () const
Get the \(y \) directly (alias).
double absrapidity () const
Get the \(|y| \) directly.
double absrap () const
Get the \(|y| \) directly (alias).
double azimuthalAngle (const PhiMapping mapping=ZERO_2PI) const
Azimuthal angle \(\phi \).
double phi (const PhiMapping mapping=ZERO_2PI) const
Get the \(\phi \) directly.
Vector3 p3 () const
Get the 3-momentum directly.
double p () const
Get the 3-momentum magnitude directly.
double p2 () const
Get the 3-momentum magnitude-squared directly.
Vector3 ptvec () const
Get the transverse 3-momentum directly.
Vector3 pTvec () const
Get the transverse 3-momentum directly.
double px () const
x component of momentum.
double py () const
y component of momentum.
double pz () const
z component of momentum.
double px2 () const
x component of momentum, squared.
double py2 () const
y component of momentum, squared.
double pz2 () const
z component of momentum, squared.
double polarAngle () const
Angle subtended by the 3-vector and the z-axis.
double theta () const
Synonym for polarAngle.
double angle (const ParticleBase &v) const
Angle between this vector and another.
double angle (const FourVector &v) const
Angle between this vector and another.
double angle (const Vector3 &v3) const
Angle between this vector and another (3-vector)
double dot (const ParticleBase &v) const
Lorentz dot product between this 4-vector and another.
double dot (const FourVector &v) const
Angle between this 4-vector and another.
Detailed Description
A charged lepton meta-particle created by clustering photons close to the bare lepton.
Todo:
Remove completely – it's unnecessary and too confusing (esp. between copying & aggregating)
Deprecated:
Just use Particle.constituents() now.
Constructor & Destructor Documentation
DressedLepton()
Rivet::DressedLepton::DressedLepton (const Particle & lepton, const Particles & photons, bool momsum = true)
Components constructor
Note
This is not a copy constructor, hence the explicit second argument even if empty
Member Function Documentation
addPhoton()
void Rivet::DressedLepton::addPhoton (const Particle & p, bool momsum = true)
Add a photon to the dressed lepton
Todo:
Deprecate and override add/setConstituents instead?
ancestors() [1/2]
Particles Rivet::Particle::ancestors (const Cut & c = Cuts::OPEN, bool only_physical = true) const inherited
Get a list of the ancestors of the current particle (with optional selection Cut)
Note
By default only physical ancestors, with status=2, are returned.
This is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::Particle::ancestors(), Rivet::Particle::hasAncestorWith(), and Rivet::Particle::hasParentWithout().
ancestors() [2/2]
Particles Rivet::Particle::ancestors (const ParticleSelector & f, bool only_physical = true) const inline inherited
Get a list of the direct parents of the current particle (with selector function)
Note
By default only physical ancestors, with status=2, are returned.
This is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::ancestors(), and Rivet::filter_select().
children()
Particles Rivet::Particle::children (const Cut & c = Cuts::OPEN) const inherited
Get a list of the direct descendants from the current particle (with optional selection Cut)
Todo:
isDecayed? How to restrict to physical particles?
Referenced by Rivet::Particle::children(), Rivet::Particle::hasChildWith(), Rivet::Particle::isLastWith(), Rivet::Particle::isPrompt(), Rivet::PartonicTops::project(), Rivet::TAU_EFF_ATLAS_RUN1(), and Rivet::TAU_EFF_ATLAS_RUN2().
closestApproach()
Vector3 Rivet::Particle::closestApproach () const inline inherited
Find the point of closest approach to the primary vertex.
Todo:
Check that this works with all angles
References Rivet::Particle::origin(), Rivet::FourVector::perp(), Rivet::ParticleBase::phi(), and Rivet::ParticleBase::theta().
constituentLepton()
const Particle& Rivet::DressedLepton::constituentLepton () const inline
Retrieve the bare lepton (alias)
Deprecated:
Prefer the more physicsy bareLepton()
References bareLepton().
constituentPhotons()
const Particles Rivet::DressedLepton::constituentPhotons () const inline
Retrieve the clustered photons (alias)
Deprecated:
Prefer the shorter photons()
References photons().
constituents() [1/6]
const Particles& Rivet::Particle::constituents () const inline inherited
Direct constituents of this particle, returned by reference.
The returned vector will be empty if this particle is non-composite, and its entries may themselves be composites.
Referenced by Rivet::Particle::constituents(), Rivet::Particle::isComposite(), and photons().
constituents() [2/6]
const Particles Rivet::Particle::constituents (const ParticleSorter & sorter) const inline inherited
Direct constituents of this particle, sorted by a functor.
Note
Returns a copy, thanks to the sorting
References Rivet::Particle::constituents(), and Rivet::sortBy().
constituents() [3/6]
const Particles Rivet::Particle::constituents (const Cut & c) const inline inherited
Direct constituents of this particle, filtered by a Cut.
Note
Returns a copy, thanks to the filtering
References Rivet::Particle::constituents(), and Rivet::filter_select().
constituents() [4/6]
const Particles Rivet::Particle::constituents (const Cut & c, const ParticleSorter & sorter) const inline inherited
Direct constituents of this particle, sorted by a functor.
Note
Returns a copy, thanks to the filtering and sorting
References Rivet::Particle::constituents(), and Rivet::sortBy().
constituents() [5/6]
const Particles Rivet::Particle::constituents (const ParticleSelector & selector) const inline inherited
Direct constituents of this particle, filtered by a selection functor.
Note
Returns a copy, thanks to the filtering
References Rivet::Particle::constituents(), and Rivet::filter_select().
constituents() [6/6]
const Particles Rivet::Particle::constituents (const ParticleSelector & selector, const ParticleSorter & sorter) const inline inherited
Direct constituents of this particle, filtered and sorted by functors.
Note
Returns a copy, thanks to the filtering and sorting
References Rivet::Particle::constituents(), Rivet::Particle::rawConstituents(), and Rivet::sortBy().
DEPRECATED()
Rivet::Particle::DEPRECATED ("Too vague: use fromHadron) || fromPromptTau(, or isDirect()") const inline inherited
Determine whether the particle is from a hadron or tau decay.
Specifically, walk up the ancestor chain until a status 2 hadron or tau is found, if at all.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::fromHadron(), Rivet::Particle::fromPromptTau(), and Rivet::Particle::isDirect().
fromBottom()
bool Rivet::Particle::fromBottom () const inherited
Determine whether the particle is from a b-hadron decay.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::fromBottom(), and Rivet::Particle::hasAncestorWithout().
fromCharm()
bool Rivet::Particle::fromCharm () const inherited
Determine whether the particle is from a c-hadron decay.
Note
If a hadron contains b and c quarks it is considered a bottom hadron and NOT a charm hadron.
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::fromCharm(), and Rivet::Particle::hasAncestorWithout().
fromHadron()
bool Rivet::Particle::fromHadron () const inherited
Determine whether the particle is from a hadron decay.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::Particle::DEPRECATED(), Rivet::fromHadron(), and Rivet::Particle::hasAncestorWithout().
fromHadronicTau()
bool Rivet::Particle::fromHadronicTau (bool prompt_taus_only = false) const inherited
Determine whether the particle is from a tau which decayed hadronically.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::Particle::fromPromptTau().
fromPromptTau()
bool Rivet::Particle::fromPromptTau () const inline inherited
Determine whether the particle is from a prompt tau decay.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::fromHadronicTau(), and Rivet::Particle::fromTau().
Referenced by Rivet::Particle::DEPRECATED(), and Rivet::fromPromptTau().
fromTau()
bool Rivet::Particle::fromTau (bool prompt_taus_only = false) const inherited
Determine whether the particle is from a tau decay.
Note
This question is valid in MC, but may not be perfectly answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::Particle::fromPromptTau(), Rivet::fromTau(), and Rivet::Particle::hasAncestorWithout().
hasAncestor()
bool Rivet::Particle::hasAncestor (PdgId pid, bool only_physical = true) const inherited
Check whether a given PID is found in the particle's ancestor list
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
Deprecated:
Prefer hasAncestorWith(Cuts::pid == pid) etc.
Referenced by Rivet::hasAncestor(), Rivet::Particle::hasAncestorWithout(), and Rivet::PartonicTops::project().
hasAncestorWith() [1/2]
bool Rivet::Particle::hasAncestorWith (const ParticleSelector & f, bool only_physical = true) const inline inherited
Check whether any particle in the particle's ancestor list has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::ancestors().
Referenced by Rivet::hasAncestorWith(), and Rivet::Particle::hasAncestorWithout().
hasAncestorWith() [2/2]
bool Rivet::Particle::hasAncestorWith (const Cut & c, bool only_physical = true) const inherited
Check whether any particle in the particle's ancestor list has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasAncestorWithout() [1/2]
bool Rivet::Particle::hasAncestorWithout (const ParticleSelector & f, bool only_physical = true) const inline inherited
Check whether any particle in the particle's ancestor list does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::fromBottom(), Rivet::Particle::fromCharm(), Rivet::Particle::fromHadron(), Rivet::Particle::fromTau(), Rivet::Particle::hasAncestor(), Rivet::Particle::hasAncestorWith(), and Rivet::ParticleBase::p().
Referenced by Rivet::hasAncestorWithout().
hasAncestorWithout() [2/2]
bool Rivet::Particle::hasAncestorWithout (const Cut & c, bool only_physical = true) const inherited
Check whether any particle in the particle's ancestor list does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasChildWith() [1/2]
bool Rivet::Particle::hasChildWith (const ParticleSelector & f) const inline inherited
Check whether any direct child of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::children().
Referenced by Rivet::hasChildWith(), Rivet::Particle::hasChildWithout(), Rivet::hasHadronicDecay(), and Rivet::hasLeptonicDecay().
hasChildWith() [2/2]
bool Rivet::Particle::hasChildWith (const Cut & c) const inherited
Check whether any direct child of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasChildWithout() [1/2]
bool Rivet::Particle::hasChildWithout (const ParticleSelector & f) const inline inherited
Check whether any direct child of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::allDescendants(), Rivet::Particle::hasChildWith(), and Rivet::ParticleBase::p().
Referenced by Rivet::hasChildWithout().
hasChildWithout() [2/2]
bool Rivet::Particle::hasChildWithout (const Cut & c) const inherited
Check whether any direct child of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasDescendantWith() [1/2]
bool Rivet::Particle::hasDescendantWith (const ParticleSelector & f, bool remove_duplicates = true) const inline inherited
Check whether any descendant of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::allDescendants().
Referenced by Rivet::hasDescendantWith(), and Rivet::Particle::hasDescendantWithout().
hasDescendantWith() [2/2]
bool Rivet::Particle::hasDescendantWith (const Cut & c, bool remove_duplicates = true) const inherited
Check whether any descendant of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasDescendantWithout() [1/2]
bool Rivet::Particle::hasDescendantWithout (const ParticleSelector & f, bool remove_duplicates = true) const inline inherited
Check whether any descendant of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::hasDescendantWith(), Rivet::ParticleBase::p(), and Rivet::Particle::stableDescendants().
Referenced by Rivet::hasDescendantWithout().
hasDescendantWithout() [2/2]
bool Rivet::Particle::hasDescendantWithout (const Cut & c, bool remove_duplicates = true) const inherited
Check whether any descendant of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasParent()
bool Rivet::Particle::hasParent (PdgId pid) const inherited
Check whether a given PID is found in the particle's parent list
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
Deprecated:
Prefer e.g. hasParentWith(Cut::pid == 123)
Referenced by Rivet::Particle::hasParentWithout().
hasParentWith() [1/2]
bool Rivet::Particle::hasParentWith (const ParticleSelector & f) const inline inherited
Check whether any particle in the particle's parent list has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::parents().
Referenced by Rivet::hasParentWith(), and Rivet::Particle::hasParentWithout().
hasParentWith() [2/2]
bool Rivet::Particle::hasParentWith (const Cut & c) const inherited
Check whether any particle in the particle's parent list has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasParentWithout() [1/2]
bool Rivet::Particle::hasParentWithout (const ParticleSelector & f) const inline inherited
Check whether any particle in the particle's parent list does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::ancestors(), Rivet::Particle::hasParent(), Rivet::Particle::hasParentWith(), and Rivet::ParticleBase::p().
Referenced by Rivet::hasParentWithout().
hasParentWithout() [2/2]
bool Rivet::Particle::hasParentWithout (const Cut & c) const inherited
Check whether any particle in the particle's parent list does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasStableDescendantWith() [1/2]
bool Rivet::Particle::hasStableDescendantWith (const ParticleSelector & f) const inline inherited
Check whether any stable descendant of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::stableDescendants().
Referenced by Rivet::hasStableDescendantWith(), and Rivet::Particle::hasStableDescendantWithout().
hasStableDescendantWith() [2/2]
bool Rivet::Particle::hasStableDescendantWith (const Cut & c) const inherited
Check whether any stable descendant of this particle has the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
hasStableDescendantWithout() [1/2]
bool Rivet::Particle::hasStableDescendantWithout (const ParticleSelector & f) const inline inherited
Check whether any stable descendant of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::Particle::flightLength(), Rivet::Particle::hasStableDescendantWith(), and Rivet::ParticleBase::p().
Referenced by Rivet::hasStableDescendantWithout().
hasStableDescendantWithout() [2/2]
bool Rivet::Particle::hasStableDescendantWithout (const Cut & c) const inherited
Check whether any stable descendant of this particle does not have the requested property
Note
This question is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
isDirect()
bool Rivet::Particle::isDirect (bool allow_from_direct_tau = false, bool allow_from_direct_mu = false) const inherited
Shorthand definition of 'promptness' based on set definition flags.
A "direct" particle is one directly connected to the hard process. It is a preferred alias for "prompt", since it has no confusing implications about distinguishability by timing information.
The boolean arguments allow a decay lepton to be considered direct if its parent was a "real" direct lepton.
Note
This one doesn't make any judgements about final-stateness
Referenced by Rivet::Particle::DEPRECATED(), Rivet::isDirect(), and Rivet::Particle::isPrompt().
isSame()
bool Rivet::Particle::isSame (const Particle & other) const inline inherited
Compare particles, based on "external" characteristics, with a little angular tolerance
Note
Not a deep comparison: GenParticle ptr and constituents are not used in the comparison
References Rivet::isZero(), Rivet::ParticleBase::mom(), Rivet::operator<<(), Rivet::Particle::origin(), Rivet::ParticleBase::p(), and Rivet::Particle::pid().
Referenced by Rivet::isSame().
operator ConstGenParticlePtr()
Rivet::Particle::operator ConstGenParticlePtr () const inline explicit inherited
Cast operator for conversion to GenParticle*
Note
Not implicit since that would enable accidental Particl::operator== comparisons
References Rivet::Particle::genParticle().
parents() [1/2]
Particles Rivet::Particle::parents (const Cut & c = Cuts::OPEN) const inherited
Get a list of the direct parents of the current particle (with optional selection Cut)
Note
This is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
Referenced by Rivet::Particle::hasParentWith(), Rivet::Particle::isFirstWith(), Rivet::Particle::parents(), and Rivet::Particle::rawConstituents().
parents() [2/2]
Particles Rivet::Particle::parents (const ParticleSelector & f) const inline inherited
Get a list of the direct parents of the current particle (with selector function)
Note
This is valid in MC, but may not be answerable experimentally – use this function with care when replicating experimental analyses!
References Rivet::filter_select(), and Rivet::Particle::parents().
rawConstituents() [1/6]
Particles Rivet::Particle::rawConstituents () const inherited
Fundamental constituents of this particle.
Note
Returns {{*this}} if this particle is non-composite.
Referenced by Rivet::Particle::constituents(), and Rivet::Particle::rawConstituents().
rawConstituents() [2/6]
const Particles Rivet::Particle::rawConstituents (const ParticleSorter & sorter) const inline inherited
Fundamental constituents of this particle, sorted by a functor.
Note
Returns a copy, thanks to the sorting
References Rivet::Particle::rawConstituents(), and Rivet::sortBy().
rawConstituents() [3/6]
const Particles Rivet::Particle::rawConstituents (const Cut & c) const inline inherited
Fundamental constituents of this particle, filtered by a Cut.
Note
Returns a copy, thanks to the filtering
References Rivet::filter_select(), and Rivet::Particle::rawConstituents().
rawConstituents() [4/6]
const Particles Rivet::Particle::rawConstituents (const Cut & c, const ParticleSorter & sorter) const inline inherited
Fundamental constituents of this particle, sorted by a functor.
Note
Returns a copy, thanks to the filtering and sorting
References Rivet::Particle::rawConstituents(), and Rivet::sortBy().
rawConstituents() [5/6]
const Particles Rivet::Particle::rawConstituents (const ParticleSelector & selector) const inline inherited
Fundamental constituents of this particle, filtered by a selection functor.
Note
Returns a copy, thanks to the filtering
References Rivet::filter_select(), and Rivet::Particle::rawConstituents().
rawConstituents() [6/6]
const Particles Rivet::Particle::rawConstituents (const ParticleSelector & selector, const ParticleSorter & sorter) const inline inherited
Fundamental constituents of this particle, filtered and sorted by functors.
Note
Returns a copy, thanks to the filtering and sorting
References Rivet::Particle::parents(), Rivet::Particle::rawConstituents(), and Rivet::sortBy().
stableDescendants()
Particles Rivet::Particle::stableDescendants (const Cut & c = Cuts::OPEN) const inherited
Get a list of all the stable descendants from the current particle (with optional selection Cut)
Todo:
Use recursion through replica-avoiding MCUtils functions to avoid bookkeeping duplicates
Insist that the current particle is post-hadronization, otherwise throw an exception?
Referenced by Rivet::Particle::hasDescendantWithout(), Rivet::Particle::hasStableDescendantWith(), and Rivet::Particle::stableDescendants().
The documentation for this class was generated from the following file:
/home/andy/proj/hep/rivet-31x/include/Rivet/Projections/DressedLeptons.hh