Rivet: Nucleus/ion functions
Nucleus/ion functions
Functions
bool Rivet::PID::isNucleus (int pid)
Is this a nucleus PID?
int Rivet::PID::nuclZ (int pid)
int Rivet::PID::nuclA (int pid)
int Rivet::PID::nuclNlambda (int pid)
Detailed Description
Function Documentation
isNucleus()
bool Rivet::PID::isNucleus (int pid) inline
Is this a nucleus PID?
This implements the 2006 Monte Carlo nuclear code scheme. Ion numbers are +/- 10LZZZAAAI. AAA is A - total baryon number ZZZ is Z - total charge L is the total number of strange quarks. I is the isomer number, with I=0 corresponding to the ground state.
Referenced by Rivet::PID::nuclA(), Rivet::PID::nuclNlambda(), and Rivet::PID::nuclZ().
nuclA()
int Rivet::PID::nuclA (int pid) inline
Get the atomic weight (number of nucleons) in a nucleus/ion
Note
Ion numbers are +/- 10LZZZAAAI.
References Rivet::PID::isNucleus().
nuclNlambda()
int Rivet::PID::nuclNlambda (int pid) inline
If this is a nucleus (ion), get nLambda
Note
Ion numbers are +/- 10LZZZAAAI.
References Rivet::PID::isNucleus().
nuclZ()
int Rivet::PID::nuclZ (int pid) inline
Get the atomic number (number of protons) in a nucleus/ion
Note
Ion numbers are +/- 10LZZZAAAI.
References Rivet::PID::isNucleus().