Rivet: Other classifiers
Other classifiers
Functions
bool Rivet::PID::isGenSpecific (int pid)
Determine if the PID is in the generator-specific range.
bool Rivet::PID::isResonance (int pid)
bool Rivet::PID::isTransportable (int pid)
Detailed Description
Function Documentation
isResonance()
bool Rivet::PID::isResonance (int pid) inline
Determine if the PID is that of an EW scale resonance
Todo:
Also include SUSY, technicolor, etc. etc.? Maybe via a isStandardModel(pid) function, but there are stable BSM particles (in principle)
References Rivet::PID::isHiggs(), Rivet::PID::isTop(), Rivet::PID::isW(), and Rivet::PID::isZ().
isTransportable()
bool Rivet::PID::isTransportable (int pid) inline
Check the PID for usability in transport codes like Geant4
Todo:
Should exclude neutrinos/LSP, since the ATLAS G4 interface deletes them immediately?
What about long-lived particles... could be BSM but need to be transported
References Rivet::PID::isHadron(), Rivet::PID::isLepton(), and Rivet::PID::isPhoton().