Rivet: Charge functions
Charge functions
Functions
int Rivet::PID::charge3 (int pid)
Three times the EM charge (as integer)
int Rivet::PID::threeCharge (int pid)
int Rivet::PID::abscharge3 (int pid)
Return the absolute value of 3 times the EM charge.
double Rivet::PID::charge (int pid)
Return the EM charge (as floating point)
double Rivet::PID::abscharge (int pid)
Return the EM charge (as floating point)
Detailed Description
Function Documentation
charge3()
int Rivet::PID::charge3 (int pid) inline
Three times the EM charge (as integer)
Todo:
Is this sufficiently general? Why only gluino in g+q+qbar? Better to recurse to the related SM hadron code?
Referenced by Rivet::PID::abscharge3(), Rivet::PID::charge(), Rivet::Particle::charge3(), Rivet::PID::isCharged(), Rivet::PID::isNeutral(), and Rivet::PID::threeCharge().
threeCharge()
int Rivet::PID::threeCharge (int pid) inline
Alias for charge3
Deprecated:
Prefer charge3
References Rivet::PID::charge3().