Rivet: Particle pair functions
Particle pair functions
Functions for Particles
Functions
PdgIdPair Rivet::pids (const ParticlePair &pp)
Detailed Description
Function Documentation
pids()
PdgIdPair Rivet::pids (const ParticlePair & pp) inline
Get the PDG ID codes of a ParticlePair
Todo:
Make ParticlePair a custom class instead?
References Rivet::sum().
Referenced by Rivet::beamIds(), Rivet::Beam::beamIds(), and Rivet::Jet::containsPID().