Rivet: Analysis object manipulation functions
Analysis object manipulation functions
Functions
map< string, YODA::AnalysisObjectPtr > Rivet::getRefData (const string &papername)
string Rivet::getDatafilePath (const string &papername)
Get the file system path to the reference file for this paper.
template<typename T >
bool Rivet::aocopy (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst)
template<typename T >
bool Rivet::aocopy (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst, double scale)
template<typename T >
bool Rivet::aoadd (YODA::AnalysisObjectPtr dst, YODA::AnalysisObjectPtr src, double scale)
bool Rivet::copyao (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst, double scale=1.0)
bool Rivet::addaos (YODA::AnalysisObjectPtr dst, YODA::AnalysisObjectPtr src, double scale)
template<typename TPtr >
bool Rivet::bookingCompatible (TPtr a, TPtr b)
bool Rivet::bookingCompatible (CounterPtr, CounterPtr)
bool Rivet::bookingCompatible (YODA::CounterPtr, YODA::CounterPtr)
bool Rivet::bookingCompatible (YODA::Scatter1DPtr a, YODA::Scatter1DPtr b)
bool Rivet::bookingCompatible (YODA::Scatter2DPtr a, YODA::Scatter2DPtr b)
bool Rivet::bookingCompatible (YODA::Scatter3DPtr a, YODA::Scatter3DPtr b)
Detailed Description
Function Documentation
addaos()
bool Rivet::addaos (YODA::AnalysisObjectPtr dst, YODA::AnalysisObjectPtr src, double scale)
If dst is the same subclass as src, scale the contents of src with scale and add it to dst and return true. Otherwise return false.
Referenced by Rivet::aoadd().
aoadd()
template<typename T > bool Rivet::aoadd (YODA::AnalysisObjectPtr dst, YODA::AnalysisObjectPtr src, double scale) inline
If dst and src both are of same subclass T, add the contents of src into dst and return true. Otherwise return false.
References Rivet::addaos(), and Rivet::copyao().
aocopy() [1/2]
template<typename T > bool Rivet::aocopy (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst) inline
If dst and src both are of same subclass T, copy the contents of src into dst and return true. Otherwise return false.
aocopy() [2/2]
template<typename T > bool Rivet::aocopy (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst, double scale) inline
If dst and src both are of same subclass T, copy the contents of src into dst and return true. Otherwise return false. The scale argument will be ued to scale the weights of non-scatter types, cf. aoadd().
bookingCompatible()
template<typename TPtr > bool Rivet::bookingCompatible (TPtr a, TPtr b) inline
Check if two analysis objects have the same binning or, if not binned, are in other ways compatible.
Referenced by Rivet::Analysis::addAnalysisObject(), and Rivet::Analysis::registerAO().
copyao()
bool Rivet::copyao (YODA::AnalysisObjectPtr src, YODA::AnalysisObjectPtr dst, double scale = 1.0)
If dst is the same subclass as src, copy the contents of src into dst and return true. Otherwise return false.
Referenced by Rivet::aoadd().
getDatafilePath()
string Rivet::getDatafilePath (const string & papername)
Get the file system path to the reference file for this paper.
Todo:
Also provide a Scatter3D getRefData() version?
getRefData()
map<string, YODA::AnalysisObjectPtr> Rivet::getRefData (const string & papername)
Function to get a map of all the refdata in a paper with the given papername.