Rivet: Histogram reference data
Histogram reference data
Functions
const std::map< std::string, YODA::AnalysisObjectPtr > & Rivet::Analysis::refData () const
Get all reference data objects for this analysis.
template<typename T = YODA::Scatter2D>
const T & Rivet::Analysis::refData (const string &hname) const
template<typename T = YODA::Scatter2D>
const T & Rivet::Analysis::refData (unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId) const
Detailed Description
Function Documentation
refData() [1/2]
template<typename T = YODA::Scatter2D> const T& Rivet::Analysis::refData (const string & hname) const inline protected
Get reference data for a named histo
Todo:
SFINAE to ensure that the type inherits from YODA::AnalysisObject?
References MSG_ERROR, MSG_TRACE, and Rivet::Analysis::name().
refData() [2/2]
template<typename T = YODA::Scatter2D> const T& Rivet::Analysis::refData (unsigned int datasetId, unsigned int xAxisId, unsigned int yAxisId) const inline protected
Get reference data for a numbered histo
Todo:
SFINAE to ensure that the type inherits from YODA::AnalysisObject?
References Rivet::Analysis::book(), Rivet::Analysis::mkAxisCode(), and Rivet::Analysis::name().