#! /usr/bin/env bash

DIR=`dirname $0`
RANKFILES=$(echo ${DIR}/*.rank)
BASECMD='${DIR}/mk-coverage-html ${DIR}/inspire-*.rhd.json -r "$RANKFILES" -R'
test -n "$UPDATE" && UPDATE='--update-ranking'
test -n "$V" && VERB="-v"

eval "$BASECMD $UPDATE $VERB"
if [[ -z "$UPDATE" ]]; then
    eval "$BASECMD -SI $VERB"
    eval "$BASECMD -S $VERB"
    eval "$BASECMD -I $VERB"
    eval "$BASECMD -s $VERB"
    eval "$BASECMD -i $VERB"
fi
