#! /usr/bin/env python3

from __future__ import division, print_function

"""\
%prog <file.rhd.json> [<file.rhd.json> ...]

TODO:
 - do Rivet lookup in this script, not the JSON-maker
 - get and write year of publication in table
"""

import argparse
ap = argparse.ArgumentParser(usage=__doc__)
ap.add_argument("JSONFILES", metavar="file", nargs="+",
                help="JSON Inspire xref file to read")
ap.add_argument("-r", "--ranking", dest="RANKFILES", metavar="file", action="append", default=[],
                help="lists of Inspire IDs to exclude, suppress, and highlight")
ap.add_argument("-R", "--reverse", dest="REVERSE", action="store_true", default=False,
                help="show list *reverse* ordered in Inspire ID")
ap.add_argument("-s", "--only-searches", dest="ONLYSEARCHES", action="store_true", default=False,
                help="only show search analyses")
ap.add_argument("-S", "--no-searches", dest="NOSEARCHES", action="store_true", default=False,
                help="exclude search analyses")
ap.add_argument("-i", "--only-heavyion", dest="ONLYHEAVYION", action="store_true", default=False,
                help="only show heavy ion analyses")
ap.add_argument("-I", "--no-heavyion", dest="NOHEAVYION", action="store_true", default=False,
                help="exclude heavy ion analyses")
ap.add_argument("-o", "--outfile", dest="OUTFILE", default=None,
                help="output HTML filename")
ap.add_argument("--basename", dest="BASENAME", default="rivet-coverage",
                help="the base name for output files [default=%(default)s]")
ap.add_argument("--update-ranking", dest="UPDATERANK", action="store_true", default=False,
                help="update the per-experiment ranking files")
ap.add_argument("--list-inputs", dest="LISTINPUTS", action="store_true", default=False,
                help="list the input files at the end of the HTML")
ap.add_argument("-v", "--verbose", dest="VERBOSE", action="store_true", default=False,
                help="print debug info to the terminal")
args = ap.parse_args()


import datetime
now = datetime.datetime.now()

## Experiment (grouping) names and regex patterns
import re
EXPTS = ["ALICE", "ATLAS", "CMS", "LHCb", "Forward", "HERA", "EE-HIGH", "EE-LOW", "Tevatron", "RHIC", "SPS", "Other"]
EXPT_PATTS = ["ALICE", "ATLAS", "CMS", "LHCb", "LHCF|TOTEM", "H1|ZEUS|HERMES", "ALEPH|DELPHI|L3|L3\+C|OPAL|SLD|LEP|TASSO|JADE|AMY|TOPAZ|MAC|VENUS|CELLO|TPC|TPC/TWO|TPC/TWO-GAMMA|TPC-TWO-GAMMA|HRS|PLUTO|MARK-J|MARK-II|MARKJ|MARKII", "BABAR|KEDR|DESY-HAMBURG-HEIDELBERG-MUNICH|AACHEN-DESY-ANNECY(LAPP)-MIT-NIKHEF-BEIJING|BELLE|BELLE-II|CLEO|CLEO-II|CUSB|ARGUS|SND|CMD|CMD2|CMD-2|CMD-3|CMD3|DM1|DM2|DM1-DM2|KLOE|KLOE-2|BES|BESIII|OLYA|FENICE|LENA|DASP|MARK-I|MARKI|MUPI|NMD|DESY147|MD1|CRYSTAL|CRYSTAL_BALL|ND|GAMMAGAMMA|BBAR|AACHEN-DESY-ANNECY\(LAPP\)-MIT-NIKHEF-BEIJING|MARK-III", "CDF|D0|E735", "STAR|PHENIX", "COMPASS|NA48|NA49|EHS/NA22|NA22"]
EXPT_REOBJS = [re.compile(patt, re.I) for patt in EXPT_PATTS]

## Add the rivet Python module build dir(s) to the Python module path, then import
import os, sys
pybuild = os.path.abspath(os.path.join(os.getcwd(), "..", "..", "pyext", "build"))
pydirs = [os.path.join(pybuild, d) for d in os.listdir(pybuild)
          if re.match(r"lib\..*-.*-%d\.%d" % (sys.version_info[0], sys.version_info[1]), d)]
sys.path = pydirs + sys.path
import rivet

## Add info file locations
from glob import glob
dirpatt = os.path.join(os.getcwd(), "..", "..", "analyses", "plugin*")
for d in glob(dirpatt):
    #print(d)
    rivet.addAnalysisDataPath(os.path.abspath(d))

## Read data from JSON files
records = {}
import json
for jsonfile in args.JSONFILES:
    with open(jsonfile) as jf:
        recs = json.load(jf)
        if args.VERBOSE:
            print("Reading {} records from {}".format(len(recs), jsonfile))
        records.update(recs)
records = {int(k) : v for k, v in records.items()}
if args.VERBOSE:
    print("Read total of {} records".format(len(records)))

## Rivet analyses to cross-reference
ranas = {}
for aname in rivet.AnalysisLoader.analysisNames():
    ana = rivet.AnalysisLoader.getAnalysis(aname)
    # TODO: all anas *should* have an Inspire ID...
    try:
        # print(aname, ":", ana.inspireId(), ":")
        iAnal=int(ana.inspireId())
        if iAnal in records and not records[iAnal][1] :
            records[iAnal][1] = ana.experiment()
        ranas.setdefault(iAnal, []).append(ana.name())
    except:
        pass


## Read Inspire IDs from ranking files
blacklist, greylist, hotlist = [], [], []
assigned = {}
comment  = {}
for rankfilestr in args.RANKFILES:
    for rankfile in rankfilestr.split(" "):
        with open(rankfile) as rf:
            if args.VERBOSE:
                print("Reading rankings from {}".format(rankfile))
            for line in rf:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                tokens = line.split()
                ins = int(tokens[0])
                code = tokens[1]
                if code == "X":
                    blacklist.append(ins)
                elif code == "?":
                    greylist.append(ins)
                elif code == "!":
                    hotlist.append(ins)
                # Detect an optional assigned email address
                last = tokens[-1]
                if "@" in last:
                    if last.startswith("<") and last.endswith(">"):
                        last = last[1:-1]
                    assigned[ins] = last
                # Detect an optional comment
                if line.count("#") == 2:
                    comment[ins] = line.split("#")[1]


## Add rankings/tags to the record
tmp = {}
for ins, rec in records.items():

    ## Sanitise title and experiment
    rec[0] = (rec[0] or "[NO TITLE]").replace("\n", " ")
    rec[1] = (rec[1] or "UNKNOWN").upper().split()[0].strip()

    ## Ranking
    code = "default"
    if ins in ranas:
        code = "rivet"
    elif ins in greylist:
        code = "grey"
    elif ins in blacklist:
        code = "black"
    elif ins in hotlist:
        code = "hot"

    ## Tags
    import re
    title = rec[0] or ""
    if "search" in title.lower():
        code += " search"
    if any(re.search(x, title) is not None for x in ["Pb", "Xe", "Au", "U+U", "gold", "lead[ ,$]", "xenon", "heavy[- ]ion"]):
        code += " heavyion"

    rm = False
    rm |= args.ONLYSEARCHES and not "search" in code
    rm |= args.NOSEARCHES and "search" in code
    rm |= args.ONLYHEAVYION and not "heavyion" in code
    rm |= args.NOHEAVYION and "heavyion" in code

    #if rm:
    #    del records[ins]
    #else:
    #    rec.append(code)
    if not rm:
        tmp[ins] = rec + [code]
records = tmp

## Group and count records by experiment (and update rank file if requested)
ex_records = {}
ex_ntots, ex_ndefaults, ex_nurgents, ex_nwanteds, ex_ntargets, ex_nrivets = {}, {}, {}, {}, {}, {}
for iex, ex in enumerate(EXPTS):

    ## Name matching
    if ex != "Other":
        ex_records[ex] = {ins : rec for ins, rec in records.items()
                          if EXPT_REOBJS[iex].match(rec[1])}
    else:
        ex_records[ex] = {ins : rec for ins, rec in records.items()
                          if not any(reobj.match(rec[1]) for reobj in EXPT_REOBJS)}

    ## Count matches
    ex_ntots[ex] = len(ex_records[ex])
    ex_nrivets[ex] = len([ins for ins, rec in ex_records[ex].items() if "rivet" in rec[-1]])
    ex_ndefaults[ex] = len([ins for ins, rec in ex_records[ex].items() if "default" in rec[-1]])
    ex_nurgents[ex] = len([ins for ins, rec in ex_records[ex].items() if "hot" in rec[-1]])
    ex_nwanteds[ex] = ex_ndefaults[ex] + ex_nurgents[ex]
    ex_ntargets[ex] = ex_nwanteds[ex] + ex_nrivets[ex]

    if args.VERBOSE:
        print(ex, "#urgent/#wanted =", ex_nurgents[ex], "/", ex_nwanteds[ex])

    if args.UPDATERANK:
        if args.ONLYSEARCHES or args.NOSEARCHES or args.ONLYHEAVYION or args.NOHEAVYION:
            print("Won't update rank lists while search/HI/experiment filtering is enabled")
            sys.exit(1)
        rfname = "{}-{}.rank".format(args.BASENAME, ex.lower())
        print("Writing updated rank file to {}".format(rfname))
        SYMBS = { "default" : ".", "rivet" : ".", "grey" : "?", "black" : "X", "hot" : "!" }
        with open(rfname, "w") as rf:
            for ins, rec in sorted(ex_records[ex].items()):
                rankcode = rec[-1].split()[0]
                #rankcode = "hot"rankcodes[0] if "hot" not in rankcodes #< keep the ! marker in the file after implementation
                # line = u"{} {} {}\n".format(ins), SYMBS[code], rec[3])
                line = u"{} {} {}".format(ins, SYMBS[rankcode], rec[0])
                if ins in comment :
                    line += " #{}#".format(comment[ins])
                # print(assigned.get(ins))
                if ins in assigned:
                    #print(ins, rec[0], assigned[ins])
                    line += "  <{}>".format(assigned[ins])
                line += "\n"
                rf.write(line)

## If we're just updating the ranking files, stop here
if args.UPDATERANK:
    exit(0)


ntot = len(records)
nrivet = len([ins for ins, rec in records.items() if "rivet" in rec[-1]])
ndefault = len([ins for ins, rec in records.items() if "default" in rec[-1]])
nurgent = len([ins for ins, rec in records.items() if "hot" in rec[-1]])
nwanted = ndefault + nurgent
ntarget = nwanted + nrivet


## Register filter strings
excls = []
if args.ONLYSEARCHES:
    excls.append("searches only")
if args.NOSEARCHES:
    excls.append("no searches")
if args.ONLYHEAVYION:
    excls.append("heavy ion only")
if args.NOHEAVYION:
    excls.append("no heavy ion")


## Web page rendering (from bundled version of the Py2 package)
from simplehtml import HTML
OUT = HTML("html")
# except: #< attempt to load the Py2 package
#     import imp
#     # TODO: handle non-system (e.g. user and venv) installs... maybe call Py2 to get the path?!? Won't work on Py3-only systems
#     html = imp.load_source("html", "/usr/local/lib/python2.7/dist-packages/html.py")
#     OUT = html.HTML("html")

title = "Rivet analysis coverage"
exclstr = " ({})".format(", ".join(excls)) if excls else ""
title += exclstr

head = OUT.head(newlines=True)
head.meta(charset="utf-8")
head.title(title)
head.link("", rel="stylesheet", href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css")
head.script("MathJax.Hub.Config({ tex2jax: {inlineMath: [['$','$']]} });", type="text/x-mathjax-config", escape=False)
#head.script("", type="text/javascript", src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML", escape=False
head.script("", type="text/javascript", **{"src" : "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML", "async" : "async", "escape" : False})
head.script("", type="text/javascript", src="https://code.jquery.com/jquery-3.3.1.js", integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", crossorigin="anonymous", escape=False)
head.script("", type="text/javascript", src="https://code.jquery.com/ui/1.12.1/jquery-ui.js", integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=", crossorigin="anonymous", escape=False)
head.script("""
$(document).ready( function(){
  $("#blacktoggle").click( function(){
    var b = $("#blacktoggle"); var t = b.text();
    b.text(t.indexOf("Show") != -1 ? t.replace("Show", "Hide") : t.replace("Hide", "Show") );
    $(".black").toggle(100);
  });
  $("#greytoggle").click( function(){
    var b = $("#greytoggle"); var t = b.text();
    b.text(t.indexOf("Show") != -1 ? t.replace("Show", "Hide") : t.replace("Hide", "Show") );
    $(".grey").toggle(100);
  });
  $("#tabs").tabs();
});
""", escape=False)

style = head.style(newlines="True")
style += "html { font-family: sans; font-size: large; color: #333; }"
style += "body { padding: 2em; }"
style += "table { margin: 2em 0 2em 0; border: 0; border-collapse: collapse; text-align: left; }"
style += "table.list { border-top: 3px solid black; border-bottom: 3px solid black; }"
style += "table.list thead { border-bottom: 1px solid #333; }"
style += "table.key { border: 1px solid #333; margin: 0; }"
style += "td { padding: 15px; }"
style += "tr.ana { border-top: 1px solid #ccc; }"
style += "tr.ana td { padding-bottom: 1em; padding-top: 1em; }"
style += "a { color: #339; }"
style += "button { margin: 1em; }"
# style += ".row { margin: 1em 0 3em 0; }"
# style += ".row:after { content: ''; display: table; clear: both; }"
# style += ".col { float: left; width: 50%; }"
style += "button { border: none; margin: 0 1em 1em 0; border-radius: 1ex; color: #333; background: #ddf; padding: 1ex; }"
style += "button:hover { background: #cce; }"
style += "button:active { color: white; }"
style += "#tabs { border: 0; }"
style += ".rivet { background: #cfc; }"
style += ".hot { background: #fbb; }"
style += ".default { background: #fee; }"
style += ".grey { color: #666; background: #ddd; font-size: normal; display: none; }"
style += ".grey a { color: #669; }"
style += ".black { color: #eee; background: #333; display: none; }"
style += ".black a { color: #99c; }"
style += ".hot.assigned { background: repeating-linear-gradient(135deg, #fbb, #fbb 10px, #bd7 10px, #bd7 20px); }"
style += ".default.assigned { background: repeating-linear-gradient(135deg, #fee, #fee 10px, #de9 10px, #de9 20px); }"
style += ".grey.assigned { background: repeating-linear-gradient(135deg, #ddd, #ddd 10px, #dfd 10px, #dfd 20px); }"

body = OUT.html.body(newlines=True)
body.h1(title)
body.p().b("Rivet analyses exist for {}/{} papers = {:.0f}%. {} priority analyses required.".format(nrivet, ntarget, 100*nrivet/ntarget, nurgent))
body.p("Total number of Inspire papers scanned = {}, at {}".format(ntot, now.strftime("%Y-%m-%d")))

body.p("Breakdown by identified experiment (in development):")
t = body.table(klass="list")
th = t.thead(newlines=True)
r = th.tr(klass="thead")
r.td().b("Key")
for ex in EXPTS:
    ee = "e<sup>+</sup>e<sup>-</sup>"
    if ex == "EE-HIGH":
        r.td().b(ee + " (&ge; 12 GeV)", escape=False)
        # r.td().b("$e^+e^- (\geq 12$ GeV)")
    elif ex == "EE-LOW":
        r.td().b(ee + " (&le; 12 GeV)", escape=False)
        # r.td().b("$e^+e^- (\leq 12$ GeV)")
    else:
        r.td().b(ex)
#
tb = t.tbody(newlines=True)
r = tb.tr(klass="default")
r.td().b("Rivet wanted (total):")
for ex in EXPTS:
    r.td("{}".format(ex_nwanteds[ex]))
#
r = tb.tr(klass="hot")
r.td().b("Rivet REALLY wanted:")
for ex in EXPTS:
    r.td("{}".format(ex_nurgents[ex]))
r = tb.tr(klass="rivet")
#
r.td().b("Rivet provided:")
for ex in EXPTS:
    # txt = "{}".format(ex_nrivets[ex])
    # if ex_ntargets[ex]:
    #     txt += "<span style=\"color: #666\"> / {:d} = </span> {:.0f}%".format(ex_ntargets[ex], 100*ex_nrivets[ex]/ex_ntargets[ex])
    # r.td(txt)
    b = r.td().b("{}".format(ex_nrivets[ex]))
    if ex_ntargets[ex]:
        b.span("/{:d} = ".format(ex_ntargets[ex]), style="color: #777")
        b += "{:.0f}%".format(100*ex_nrivets[ex]/ex_ntargets[ex])

body.button("Show greylist", id="greytoggle")
body.button("Show blacklist", id="blacktoggle")

#body.input(klass="search", placeholder="Search")
#body.button("Sort by name", klass="sort", data-sort="name")

tabs = body.div(id="tabs")
u = tabs.ul()
for ex in EXPTS:
    ee = "e<sup>+</sup>e<sup>-</sup>"
    if ex == "EE-HIGH":
        u.li().a(ee + " (&ge; 12 GeV)", href="#{}expt".format(ex.lower()), escape=False)
        # u.li().a("$e^+e^-(\geq12$ GeV)", href="#{}expt".format(ex.lower()))
    elif ex == "EE-LOW":
        u.li().a(ee + " (&le; 12 GeV)", href="#{}expt".format(ex.lower()), escape=False)
        # u.li().a("$e^+e^-(\leq12$ GeV)", href="#{}expt".format(ex.lower()))
    else:
        u.li().a(ex, href="#{}expt".format(ex.lower()))

for ex in EXPTS:
    d = tabs.div(id="{}expt".format(ex.lower()))
    t = d.table(klass="list").tbody(newlines=True)
    for i, (ins, rec) in enumerate(sorted(ex_records[ex].items(), reverse=args.REVERSE)):

        expt = rec[1]
        code = rec[-1]
        if ins in assigned:
            code += " assigned"
        if expt:
            code += " {}expt".format(expt.lower())
        cell = t.tr(klass=code+" ana", newlines=True).td(newlines=False)
        # Title
        summ = u""
        summ += u"{}: {}".format(expt, rec[0])
        cell.span().b(summ)

        ## Inspire ID and link
        p = cell.p()
        sp = p.span("Inspire:")
        sp += "&nbsp;"
        sp.a(str(ins), href="http://inspirehep.net/record/{}".format(ins))

        ## arXiv ID and links
        if rec[4]:
            p += "&ensp;&middot;&ensp; "
            sp = p.span("arXiv:")
            sp += "&nbsp;"
            sp.a(str(rec[4]), href="https://arxiv.org/abs/{}".format(rec[4]))
            sp += "&nbsp;("
            sp.a(str("pdf"), href="https://arxiv.org/pdf/{}.pdf".format(rec[4]))
            sp += ")"

        ## DOI
        if rec[2]:
            p += "&ensp;&middot;&ensp;"
            sp = p.span("DOI/journal:")
            sp += "&nbsp;"
            sp.a(str(rec[2]), href="http://dx.doi.org/{}".format(rec[2]))

        ## CDS
        if rec[3]:
            p += "&ensp;&middot;&ensp; "
            sp = p.span("CDS:")
            sp += "&nbsp;"
            sp.a(str(rec[3]), href="https://cds.cern.ch/record/{}".format(rec[3]))

        ## HepData
        if rec[5]:
            p += "&ensp;&middot;&ensp; "
            sp = p.span("HepData:")
            sp += "&nbsp;"
            sp.a(str(rec[5]), href="https://hepdata.net/record/{}".format(rec[5]))

        if rec[7]:
            p += "&ensp;&middot;&ensp; "
            sp = p.span("Report IDs:")
            sp += "&nbsp;"
            sp += u", ".join(rec[7])


        ## Rivet
        if ins in ranas or ins in assigned or ins in comment:
            p = cell.span("")
            if ins in ranas:
                anas = u", ".join(ranas[ins])
                p += " "
                p.a(anas, href="https://rivet.hepforge.org/analyses/{}.html".format(ranas[ins][0]))
            ## In-progress/assignment
            if ins in assigned:
                p += " "
                p.a("IN PROGRESS: assigned to {}".format(assigned[ins]), href="mailto:{}".format(assigned[ins]))
            ## Comment
            if ins in comment:
                cell.p().span().b(comment[ins])


## Time-created footer
body.p("Generated at {}".format(now.strftime("%c")))
if args.LISTINPUTS:
    body.p("Generated from JSON files extracted from Inspire ({} papers in total):".format(ntot))
    body.p(", ".join(os.path.basename(jf) for jf in args.JSONFILES), style="font-family: monospace; font-size: smaller")


## Write out
outfile = args.OUTFILE
if not outfile:
    outfile = args.BASENAME
    exclparts = [e.replace(" ", "") for e in excls]
    if exclparts:
        outfile += "-" + "-".join(exclparts)
if not outfile.endswith(".html"):
    outfile += ".html"
print("Writing output to {} {}".format(outfile, exclstr))
with open(outfile, "wb") as hf:
    try:
      a = unicode(OUT)
    except:
      a = str(OUT)
    hf.write(a.encode("UTF-8"))
