import yoda
def patch(path, ao):
    # bin widths (needs a lot more thought, the current ones were generated by old hepdata)
    if "OPAL_1993_S2692198" in path and "d04" in path:
        for p in ao.points() :
            if "d04" in path :
                p.setXErrs(0.001)
    return ao
