#! /usr/bin/env python

usage = """%prog [analysis1 analysis2 ...]

Get SPIRES BibTeX entries for analysis info files
"""

## Parse command line options
from optparse import OptionParser
parser = OptionParser(usage=usage)
opts, args = parser.parse_args()

import rivet

## If not args supplied, use all analyses
if not args:
    args = rivet.AnalysisLoader.analysisNames()

## Make individual bibinfo files
for aname in args:
    ana = rivet.AnalysisLoader.getAnalysis(aname)
    if not ana:
        exit(1)
    sid = ana.spiresId()
    print "Getting SPIRES bib data for '%s'" % aname
    key, bibtex = rivet.spiresbib.get_bibtex_from_spires(sid)
    if key and bibtex:
        f = open(aname+".bib.info", "w")
        f.write("BibKey: %s\n" % key)
        f.write("BibTeX: '%s'\n" % bibtex)
        f.close()
    else:
        print "No BibTeX available for analysis '%s'" % aname
